package org.muybaby.shopserver.storage;

public enum StorageUsageOwnerType {
    PRODUCT_CATEGORY,
    PRODUCT_SPU,
    PRODUCT_SKU,
    PRODUCT_SPEC_VALUE,
    GUARANTEE_SERVICE,
    HOME_BANNER,
    HOME_CATEGORY_ITEM,
    HOME_PRODUCT_ITEM,
    ORDER_ITEM,
    PRODUCT_REVIEW,
    AFTER_SALE,
    PAYMENT_CONFIG,
    CUSTOMER_SERVICE_CONFIG,
    MERCHANT_PUBLICATION,
    PRODUCT_FOOD_DISCLOSURE
}
