package org.muybaby.shopserver.storage;

public enum StorageFileUsageType {
    PRODUCT_CATEGORY_ICON,
    PRODUCT_SPU_MAIN,
    PRODUCT_SPU_GALLERY,
    PRODUCT_SPU_VIDEO,
    PRODUCT_SKU_IMAGE,
    PRODUCT_SPEC_VALUE_IMAGE,
    GUARANTEE_SERVICE_ICON,
    PRODUCT_DETAIL_HTML,
    RICH_TEXT_IMAGE,
    HOME_BANNER,
    HOME_CATEGORY_IMAGE,
    HOME_PRODUCT_IMAGE,
    ORDER_ITEM_SNAPSHOT,
    PRODUCT_REVIEW_IMAGE,
    AFTER_SALE_EVIDENCE,
    PAYMENT_CONFIG_CERT,
    CUSTOMER_SERVICE_AVATAR,
    MERCHANT_BUSINESS_LICENSE,
    MERCHANT_FOOD_QUALIFICATION,
    PRODUCT_FOOD_LABEL
}
