UPDATE storage_file
SET asset_category_id = CASE purpose
    WHEN 'PRODUCT_IMAGE' THEN 1
    WHEN 'PRODUCT_SKU_IMAGE' THEN 1
    WHEN 'HOME_BANNER' THEN 2
    WHEN 'CATEGORY_ICON' THEN 3
    WHEN 'APP_ICON' THEN 4
    WHEN 'RICH_TEXT_IMAGE' THEN 5
    WHEN 'MARKETING_IMAGE' THEN 6
    WHEN 'AFTER_SALE_IMAGE' THEN 7
    WHEN 'REFUND_EVIDENCE' THEN 7
    WHEN 'PAYMENT_CERTIFICATE' THEN 8
END
WHERE asset_category_id IS NULL
  AND purpose IN (
      'PRODUCT_IMAGE',
      'PRODUCT_SKU_IMAGE',
      'HOME_BANNER',
      'CATEGORY_ICON',
      'APP_ICON',
      'RICH_TEXT_IMAGE',
      'MARKETING_IMAGE',
      'AFTER_SALE_IMAGE',
      'REFUND_EVIDENCE',
      'PAYMENT_CERTIFICATE'
  );
