-- Shop schema generation 2 baseline.
-- Cart, coupons, inventory, analytics, and order aggregates.

CREATE TABLE analytics_event (
  id bigint NOT NULL AUTO_INCREMENT,
  client_event_id varchar(64) NOT NULL,
  payload_digest varchar(64) NOT NULL,
  visitor_id varchar(64) NOT NULL,
  session_id varchar(64) NOT NULL,
  user_id bigint DEFAULT NULL,
  event_source varchar(16) NOT NULL,
  event_type varchar(32) NOT NULL,
  page_path varchar(160) NOT NULL DEFAULT '',
  source_page varchar(160) NOT NULL DEFAULT '',
  entry_scene varchar(32) NOT NULL DEFAULT '',
  search_keyword varchar(80) NOT NULL DEFAULT '',
  checkout_source varchar(20) NOT NULL DEFAULT '',
  spu_id bigint DEFAULT NULL,
  sku_id bigint DEFAULT NULL,
  quantity int DEFAULT NULL,
  occurred_at timestamp NOT NULL,
  received_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  business_date date NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_analytics_event_visitor_client UNIQUE (visitor_id,client_event_id),
  INDEX idx_analytics_event_date_type (business_date,event_type,id),
  INDEX idx_analytics_event_user_date (user_id,business_date,id),
  INDEX idx_analytics_event_session_time (visitor_id,session_id,occurred_at,id),
  INDEX idx_analytics_event_spu_type_date (spu_id,event_type,business_date,id),
  INDEX idx_analytics_event_received (received_at,id),
  INDEX idx_analytics_event_retention (business_date,id)
);

CREATE TABLE cart_item (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  sku_id bigint NOT NULL,
  quantity int NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_cart_item_user_sku UNIQUE (user_id,sku_id),
  INDEX idx_cart_item_user_updated (user_id,updated_at),
  INDEX idx_cart_item_sku (sku_id),
  INDEX idx_cart_item_updated (updated_at,id)
);

CREATE TABLE coupon_claim_record (
  id bigint NOT NULL AUTO_INCREMENT,
  template_id bigint NOT NULL,
  user_id bigint NOT NULL,
  user_coupon_id bigint NOT NULL,
  claimed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  issue_source varchar(20) NOT NULL DEFAULT 'SELF_CLAIM',
  issued_by_admin_user_id bigint DEFAULT NULL,
  issue_note varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  INDEX idx_coupon_claim_template_user (template_id,user_id,claimed_at),
  INDEX idx_coupon_claim_issue_source (issue_source,claimed_at,id),
  INDEX idx_coupon_claim_claimed (claimed_at,id)
);

CREATE TABLE coupon_template (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(80) NOT NULL,
  description varchar(255) NOT NULL DEFAULT '',
  coupon_type varchar(20) NOT NULL,
  discount_type varchar(20) NOT NULL,
  threshold_cent bigint NOT NULL DEFAULT '0',
  discount_cent bigint NOT NULL,
  scope_type varchar(20) NOT NULL DEFAULT 'ALL',
  scope_value varchar(255) NOT NULL DEFAULT '',
  strategy_key varchar(80) NOT NULL DEFAULT 'coupon.amount-off.v1',
  total_stock int NOT NULL,
  claimed_count int NOT NULL DEFAULT '0',
  per_user_limit int NOT NULL DEFAULT '1',
  valid_start_at timestamp NOT NULL,
  valid_end_at timestamp NOT NULL,
  status varchar(20) NOT NULL,
  sort_order int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  distribution_mode varchar(20) NOT NULL DEFAULT 'PUBLIC',
  audience_user_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_coupon_template_status_sort (status,sort_order,id),
  INDEX idx_coupon_template_validity (valid_start_at,valid_end_at),
  INDEX idx_coupon_template_distribution_audience (distribution_mode,audience_user_id,id)
);

CREATE TABLE order_item (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  sku_id bigint NOT NULL,
  spu_id bigint NOT NULL,
  product_title varchar(128) NOT NULL,
  product_subtitle varchar(255) NOT NULL DEFAULT '',
  main_image varchar(500) NOT NULL DEFAULT '',
  sku_image varchar(500) NOT NULL DEFAULT '',
  display_image varchar(500) NOT NULL DEFAULT '',
  sku_code varchar(64) NOT NULL,
  spec_text varchar(255) NOT NULL DEFAULT '',
  original_price_cent bigint NOT NULL DEFAULT '0',
  unit_price_cent bigint NOT NULL DEFAULT '0',
  quantity int NOT NULL,
  line_original_amount_cent bigint NOT NULL DEFAULT '0',
  line_amount_cent bigint NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  main_image_file_id bigint DEFAULT NULL,
  sku_image_file_id bigint DEFAULT NULL,
  display_image_file_id bigint DEFAULT NULL,
  unit_cost_cent bigint DEFAULT NULL,
  line_cost_cent bigint DEFAULT NULL,
  coupon_discount_allocated_cent bigint DEFAULT NULL,
  freight_allocated_cent bigint DEFAULT NULL,
  paid_amount_allocated_cent bigint DEFAULT NULL,
  retail_unit_price_cent bigint NOT NULL DEFAULT '0',
  wholesale_tier_min_quantity int DEFAULT NULL,
  refunded_quantity int NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  INDEX idx_order_item_order (order_id),
  INDEX idx_order_item_spu (spu_id),
  INDEX idx_order_item_statistics_spu_order (spu_id,order_id,sku_id),
  INDEX idx_order_item_sku_order (sku_id,order_id),
  CONSTRAINT chk_order_item_refunded_quantity CHECK (((refunded_quantity >= 0) and (refunded_quantity <= quantity)))
);

CREATE TABLE order_status_log (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  from_status varchar(20) NOT NULL DEFAULT '',
  to_status varchar(20) NOT NULL,
  event_type varchar(32) NOT NULL,
  operator_type varchar(20) NOT NULL,
  operator_id bigint DEFAULT NULL,
  description varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  after_sale_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_order_status_log_order_created (order_id,created_at,id),
  INDEX idx_order_status_log_after_sale_created (after_sale_id,created_at,id)
);

CREATE TABLE shop_order (
  id bigint NOT NULL AUTO_INCREMENT,
  order_no varchar(32) NOT NULL,
  user_id bigint NOT NULL,
  status varchar(20) NOT NULL,
  source varchar(20) NOT NULL DEFAULT 'CART',
  idempotency_key varchar(80) NOT NULL,
  product_original_amount_cent bigint NOT NULL DEFAULT '0',
  product_amount_cent bigint NOT NULL DEFAULT '0',
  user_coupon_id bigint DEFAULT NULL,
  coupon_name varchar(80) NOT NULL DEFAULT '',
  coupon_discount_cent bigint NOT NULL DEFAULT '0',
  freight_cent bigint NOT NULL DEFAULT '0',
  payable_amount_cent bigint NOT NULL DEFAULT '0',
  paid_amount_cent bigint NOT NULL DEFAULT '0',
  receiver_name varchar(64) NOT NULL DEFAULT '',
  receiver_phone varchar(32) NOT NULL DEFAULT '',
  receiver_address varchar(512) NOT NULL DEFAULT '',
  payment_transaction_id varchar(64) NOT NULL DEFAULT '',
  merchant_trade_no varchar(64) NOT NULL DEFAULT '',
  close_reason varchar(64) NOT NULL DEFAULT '',
  closed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at timestamp NULL DEFAULT NULL,
  shipped_at timestamp NULL DEFAULT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  refunding_at timestamp NULL DEFAULT NULL,
  refunded_at timestamp NULL DEFAULT NULL,
  checkout_request_digest varchar(64) NOT NULL,
  analytics_visitor_id varchar(64) DEFAULT NULL,
  analytics_session_id varchar(64) DEFAULT NULL,
  analytics_entry_scene varchar(32) NOT NULL DEFAULT '',
  app_deleted_at timestamp NULL DEFAULT NULL,
  receiver_province varchar(64) NOT NULL DEFAULT '',
  receiver_city varchar(64) NOT NULL DEFAULT '',
  receiver_district varchar(64) NOT NULL DEFAULT '',
  receiver_detail_address varchar(512) NOT NULL DEFAULT '',
  receiver_location_name varchar(128) NOT NULL DEFAULT '',
  receiver_doorplate varchar(128) NOT NULL DEFAULT '',
  payment_expires_at timestamp NULL DEFAULT NULL,
  created_timeout_claim_token varchar(36) DEFAULT NULL,
  created_timeout_claimed_at timestamp NULL DEFAULT NULL,
  created_timeout_attempts int NOT NULL DEFAULT '0',
  refund_status varchar(32) NOT NULL DEFAULT 'NONE',
  refunded_amount_cent bigint NOT NULL DEFAULT '0',
  last_refund_success_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_shop_order_user_idempotency UNIQUE (user_id,idempotency_key),
  CONSTRAINT uk_shop_order_order_no UNIQUE (order_no),
  CONSTRAINT chk_shop_order_checkout_request_digest CHECK (char_length(checkout_request_digest) = 64),
  INDEX idx_shop_order_user_status_created (user_id,status,created_at),
  INDEX idx_shop_order_admin_status_created (status,created_at,id),
  INDEX idx_shop_order_admin_receiver_phone (receiver_phone),
  INDEX idx_shop_order_statistics_paid (paid_at,user_id,id),
  INDEX idx_shop_order_paid_at (paid_at,id),
  INDEX idx_shop_order_user_paid_at (user_id,paid_at,id),
  INDEX idx_shop_order_analytics_session (analytics_visitor_id,analytics_session_id,id),
  INDEX idx_shop_order_statistics_created (created_at,id),
  INDEX idx_shop_order_user_app_visible_created (user_id,app_deleted_at,created_at,id),
  INDEX idx_shop_order_cleanup_candidate (updated_at,id),
  INDEX idx_shop_order_created_timeout (status,payment_expires_at,id),
  INDEX idx_shop_order_refund_status_updated (refund_status,updated_at,id),
  CONSTRAINT chk_shop_order_refunded_amount CHECK (((refunded_amount_cent >= 0) and (refunded_amount_cent <= paid_amount_cent)))
);

CREATE TABLE stock_lock (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  order_item_id bigint NOT NULL,
  sku_id bigint NOT NULL,
  quantity int NOT NULL,
  status varchar(20) NOT NULL,
  locked_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  restock_refund_order_id bigint DEFAULT NULL,
  restocked_at timestamp NULL DEFAULT NULL,
  restocked_quantity int NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  INDEX idx_stock_lock_order (order_id,status),
  INDEX idx_stock_lock_restock_refund (restock_refund_order_id,id),
  CONSTRAINT chk_stock_lock_restocked_quantity CHECK (((restocked_quantity >= 0) and (restocked_quantity <= quantity)))
);

CREATE TABLE stock_log (
  id bigint NOT NULL AUTO_INCREMENT,
  sku_id bigint NOT NULL,
  change_type varchar(20) NOT NULL,
  quantity_before int NOT NULL,
  quantity_delta int NOT NULL,
  quantity_after int NOT NULL,
  reason varchar(255) NOT NULL,
  operator_type varchar(20) NOT NULL,
  operator_id bigint NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  order_id bigint DEFAULT NULL,
  refund_order_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_stock_log_refund_sku_change UNIQUE (refund_order_id,sku_id,change_type),
  INDEX idx_stock_log_sku_created (sku_id,created_at),
  INDEX idx_stock_log_created_sku (created_at,sku_id,id),
  INDEX idx_stock_log_order (order_id,id)
);

CREATE TABLE user_coupon (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  template_id bigint NOT NULL,
  template_name varchar(80) NOT NULL,
  coupon_type varchar(20) NOT NULL,
  discount_type varchar(20) NOT NULL,
  threshold_cent bigint NOT NULL DEFAULT '0',
  discount_cent bigint NOT NULL,
  scope_type varchar(20) NOT NULL DEFAULT 'ALL',
  scope_value varchar(255) NOT NULL DEFAULT '',
  valid_start_at timestamp NOT NULL,
  valid_end_at timestamp NOT NULL,
  status varchar(20) NOT NULL,
  claimed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_order_id bigint DEFAULT NULL,
  locked_at timestamp NULL DEFAULT NULL,
  used_order_id bigint DEFAULT NULL,
  used_at timestamp NULL DEFAULT NULL,
  released_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_user_coupon_user_status_valid (user_id,status,valid_end_at),
  INDEX idx_user_coupon_template_user (template_id,user_id),
  INDEX idx_user_coupon_statistics_claimed (claimed_at,status,template_id),
  INDEX idx_user_coupon_statistics_used (used_at,template_id,user_id),
  INDEX idx_user_coupon_template_status_used (template_id,status,used_at,id),
  INDEX idx_user_coupon_status_valid_end (status,valid_end_at,id),
  INDEX idx_user_coupon_locked_order (locked_order_id,id),
  INDEX idx_user_coupon_used_order (used_order_id,id)
);
