-- Shop schema generation 2 baseline.
-- Database-only payment configuration, payments, refunds, and after-sales.

CREATE TABLE after_sale_evidence (
  id bigint NOT NULL AUTO_INCREMENT,
  after_sale_id bigint NOT NULL,
  file_id bigint NOT NULL,
  sort_order int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_after_sale_evidence_after_sale_sort (after_sale_id,sort_order,id)
);

CREATE TABLE after_sale_item (
  id bigint NOT NULL AUTO_INCREMENT,
  after_sale_id bigint NOT NULL,
  order_item_id bigint NOT NULL,
  sku_id bigint NOT NULL,
  order_quantity_snapshot int NOT NULL,
  paid_amount_basis_cent bigint NOT NULL,
  refunded_quantity_before int NOT NULL DEFAULT '0',
  requested_quantity int NOT NULL,
  approved_quantity int DEFAULT NULL,
  requested_amount_cent bigint NOT NULL,
  approved_amount_cent bigint DEFAULT NULL,
  restock_quantity int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_after_sale_item_sale_order_item UNIQUE (after_sale_id,order_item_id),
  INDEX idx_after_sale_item_order_item_sale (order_item_id,after_sale_id),
  CONSTRAINT chk_after_sale_item_amounts CHECK (((paid_amount_basis_cent >= 0) and (requested_amount_cent >= 0) and (requested_amount_cent <= paid_amount_basis_cent) and ((approved_amount_cent is null) or ((approved_amount_cent >= 0) and (approved_amount_cent <= requested_amount_cent) and (approved_amount_cent <= paid_amount_basis_cent))))),
  CONSTRAINT chk_after_sale_item_quantities CHECK (((order_quantity_snapshot > 0) and (refunded_quantity_before >= 0) and (refunded_quantity_before <= order_quantity_snapshot) and (requested_quantity > 0) and (requested_quantity <= (order_quantity_snapshot - refunded_quantity_before)) and ((approved_quantity is null) or ((approved_quantity >= 0) and (approved_quantity <= requested_quantity))) and (restock_quantity >= 0) and (restock_quantity <= coalesce(approved_quantity,0))))
);

CREATE TABLE after_sale_request (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  user_id bigint NOT NULL,
  after_sale_type varchar(20) NOT NULL,
  status varchar(32) NOT NULL,
  reason varchar(128) NOT NULL,
  description varchar(500) NOT NULL DEFAULT '',
  requested_amount_cent bigint NOT NULL,
  approved_amount_cent bigint DEFAULT NULL,
  audit_note varchar(255) NOT NULL DEFAULT '',
  reviewed_by bigint DEFAULT NULL,
  reviewed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  after_sale_no varchar(32) NOT NULL,
  request_key varchar(80) DEFAULT NULL,
  request_digest varchar(64) NOT NULL DEFAULT '',
  source_order_status varchar(20) NOT NULL DEFAULT '',
  return_deadline_at timestamp NULL DEFAULT NULL,
  cancelled_at timestamp NULL DEFAULT NULL,
  version bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  CONSTRAINT uk_after_sale_request_after_sale_no UNIQUE (after_sale_no),
  CONSTRAINT uk_after_sale_request_user_order_key UNIQUE (user_id,order_id,request_key),
  INDEX idx_after_sale_order_status (order_id,status),
  INDEX idx_after_sale_admin_status_created (status,created_at,id),
  INDEX idx_after_sale_admin_user_created (user_id,created_at,id),
  INDEX idx_after_sale_statistics_created (created_at,status,order_id),
  INDEX idx_after_sale_statistics_reviewed (reviewed_at,status,id)
);

CREATE TABLE after_sale_return (
  after_sale_id bigint NOT NULL,
  return_address_id bigint NOT NULL,
  contact_name varchar(64) NOT NULL,
  contact_phone varchar(32) NOT NULL,
  province varchar(64) NOT NULL DEFAULT '',
  city varchar(64) NOT NULL DEFAULT '',
  district varchar(64) NOT NULL DEFAULT '',
  detail_address varchar(255) NOT NULL,
  delivery_company_code varchar(128) NOT NULL DEFAULT '',
  delivery_company_name varchar(128) NOT NULL DEFAULT '',
  tracking_no varchar(80) NOT NULL DEFAULT '',
  user_shipped_at timestamp NULL DEFAULT NULL,
  merchant_received_at timestamp NULL DEFAULT NULL,
  inspection_result varchar(20) NOT NULL DEFAULT '',
  inspection_note varchar(255) NOT NULL DEFAULT '',
  inspected_by bigint DEFAULT NULL,
  inspected_at timestamp NULL DEFAULT NULL,
  version bigint NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (after_sale_id),
  INDEX idx_after_sale_return_tracking (delivery_company_code,tracking_no)
);

CREATE TABLE after_sale_status_log (
  id bigint NOT NULL AUTO_INCREMENT,
  after_sale_id bigint NOT NULL,
  from_status varchar(32) NOT NULL DEFAULT '',
  to_status varchar(32) NOT NULL,
  event_type varchar(48) NOT NULL,
  operator_type varchar(20) NOT NULL,
  operator_id bigint DEFAULT NULL,
  description varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_after_sale_status_log_sale_created (after_sale_id,created_at,id)
);

CREATE TABLE merchant_return_address (
  id bigint NOT NULL AUTO_INCREMENT,
  contact_name varchar(64) NOT NULL,
  contact_phone varchar(32) NOT NULL,
  province varchar(64) NOT NULL DEFAULT '',
  city varchar(64) NOT NULL DEFAULT '',
  district varchar(64) NOT NULL DEFAULT '',
  detail_address varchar(255) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  default_slot smallint DEFAULT NULL,
  version bigint NOT NULL DEFAULT '0',
  created_by bigint DEFAULT NULL,
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_merchant_return_address_default_slot UNIQUE (default_slot),
  INDEX idx_merchant_return_address_enabled_updated (enabled,updated_at,id),
  CONSTRAINT chk_merchant_return_address_default CHECK (((default_slot is null) or (default_slot = 1)))
);

CREATE TABLE payment_attempt (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  payment_order_id bigint DEFAULT NULL,
  out_trade_no varchar(64) NOT NULL,
  status varchar(32) NOT NULL,
  amount_cent bigint NOT NULL,
  error_code varchar(64) NOT NULL DEFAULT '',
  error_message varchar(255) NOT NULL DEFAULT '',
  started_at timestamp NOT NULL,
  prepay_succeeded_at timestamp NULL DEFAULT NULL,
  paid_at timestamp NULL DEFAULT NULL,
  closed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_payment_attempt_payment_order UNIQUE (payment_order_id),
  INDEX idx_payment_attempt_status_started (status,started_at,id),
  INDEX idx_payment_attempt_order_started (order_id,started_at,id),
  INDEX idx_payment_attempt_out_trade_started (out_trade_no,started_at,id),
  INDEX idx_payment_attempt_started (started_at,id)
);

CREATE TABLE payment_callback_log (
  id bigint NOT NULL AUTO_INCREMENT,
  callback_type varchar(20) NOT NULL,
  notify_id varchar(128) NOT NULL DEFAULT '',
  out_trade_no varchar(64) NOT NULL DEFAULT '',
  out_refund_no varchar(64) NOT NULL DEFAULT '',
  transaction_id varchar(64) NOT NULL DEFAULT '',
  refund_id varchar(64) NOT NULL DEFAULT '',
  event_type varchar(64) NOT NULL DEFAULT '',
  resource_digest varchar(64) NOT NULL DEFAULT '',
  raw_body_sha256 varchar(64) NOT NULL,
  status varchar(20) NOT NULL,
  error_code varchar(64) NOT NULL DEFAULT '',
  error_message varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  route_digest char(64) NOT NULL,
  PRIMARY KEY (id),
  INDEX idx_payment_callback_trade (out_trade_no,updated_at,id),
  INDEX idx_payment_callback_refund (out_refund_no,updated_at,id)
);

CREATE TABLE payment_config (
  id bigint NOT NULL AUTO_INCREMENT,
  config_name varchar(80) NOT NULL,
  app_id varchar(64) NOT NULL,
  mch_id varchar(32) NOT NULL,
  merchant_serial_no varchar(128) NOT NULL,
  api_v3_key_ciphertext text NOT NULL,
  verify_mode varchar(32) NOT NULL DEFAULT 'PUBLIC_KEY',
  wechat_public_key_id varchar(128) NOT NULL DEFAULT '',
  notify_url varchar(255) NOT NULL,
  refund_notify_url varchar(255) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  secret_cipher_version smallint NOT NULL DEFAULT 2,
  secret_key_id varchar(64) NOT NULL DEFAULT '',
  secret_revision bigint NOT NULL DEFAULT '0',
  secret_reencrypted_at timestamp NULL DEFAULT NULL,
  private_key_pem_ciphertext text,
  wechat_public_key_pem_ciphertext text,
  deleted_at timestamp NULL DEFAULT NULL,
  deleted_by bigint DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_payment_config_secret_key (secret_cipher_version,secret_key_id,id),
  CONSTRAINT chk_payment_config_cipher_v2 CHECK (secret_cipher_version = 2 AND secret_key_id <> ''),
  CONSTRAINT chk_payment_config_delete_state CHECK ((((status = 'ACTIVE') and (deleted_at is null) and (deleted_by is null)) or ((status = 'DELETED') and (enabled = false) and (deleted_at is not null) and (deleted_by is not null) and (deleted_by > 0))))
);

CREATE TABLE payment_order (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  payment_config_id bigint NOT NULL,
  out_trade_no varchar(64) NOT NULL,
  prepay_id varchar(128) NOT NULL DEFAULT '',
  transaction_id varchar(64) NOT NULL DEFAULT '',
  payer_openid varchar(128) NOT NULL DEFAULT '',
  status varchar(32) NOT NULL,
  amount_cent bigint NOT NULL,
  currency varchar(16) NOT NULL DEFAULT 'CNY',
  request_digest varchar(64) NOT NULL DEFAULT '',
  callback_digest varchar(64) NOT NULL DEFAULT '',
  last_error_code varchar(64) NOT NULL DEFAULT '',
  last_error_message varchar(255) NOT NULL DEFAULT '',
  expires_at timestamp NOT NULL,
  paid_at timestamp NULL DEFAULT NULL,
  closed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  timeout_close_claim_token varchar(36) DEFAULT NULL,
  timeout_close_claimed_at timestamp NULL DEFAULT NULL,
  timeout_close_attempts int NOT NULL DEFAULT '0',
  prepay_claim_token varchar(36) DEFAULT NULL,
  prepay_claimed_at timestamp NULL DEFAULT NULL,
  prepay_attempts int NOT NULL DEFAULT '0',
  payment_config_fingerprint char(64) NOT NULL,
  notification_route_token varchar(32) NOT NULL,
  provider_description varchar(127) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_payment_order_out_trade_no UNIQUE (out_trade_no),
  CONSTRAINT uk_payment_order_notification_route UNIQUE (notification_route_token),
  INDEX idx_payment_order_order_status (order_id,status),
  INDEX idx_payment_order_expires_status (expires_at,status),
  INDEX idx_payment_order_statistics_created (created_at,status,order_id),
  INDEX idx_payment_order_status_paid_at (status,paid_at,id),
  INDEX idx_payment_order_timeout_close (status,expires_at,id),
  INDEX idx_payment_order_prepay_claim (order_id,status,prepay_claimed_at,id),
  INDEX idx_payment_order_config_identity_updated (payment_config_id,payment_config_fingerprint,updated_at),
  CONSTRAINT chk_payment_order_config_fingerprint CHECK (char_length(payment_config_fingerprint) = 64),
  CONSTRAINT chk_payment_order_notification_route CHECK (char_length(notification_route_token) = 32)
);

CREATE TABLE payment_secret_rotation_checkpoint (
  checkpoint_name varchar(64) NOT NULL,
  cursor_value varchar(128) NOT NULL DEFAULT '',
  scan_epoch bigint NOT NULL DEFAULT '0',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (checkpoint_name)
);

CREATE TABLE refund_inventory_restock_item (
  id bigint NOT NULL AUTO_INCREMENT,
  refund_order_id bigint NOT NULL,
  after_sale_item_id bigint DEFAULT NULL,
  order_item_id bigint NOT NULL,
  stock_lock_id bigint NOT NULL,
  sku_id bigint NOT NULL,
  quantity int NOT NULL,
  restocked_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_refund_restock_order_item UNIQUE (refund_order_id,order_item_id),
  INDEX idx_refund_restock_stock_lock (stock_lock_id,refund_order_id),
  CONSTRAINT chk_refund_restock_quantity CHECK ((quantity > 0))
);

CREATE TABLE refund_order (
  id bigint NOT NULL AUTO_INCREMENT,
  after_sale_id bigint NOT NULL,
  order_id bigint NOT NULL,
  payment_order_id bigint NOT NULL,
  out_refund_no varchar(64) NOT NULL,
  refund_id varchar(64) NOT NULL DEFAULT '',
  refund_amount_cent bigint NOT NULL,
  status varchar(32) NOT NULL,
  callback_status varchar(32) NOT NULL DEFAULT '',
  callback_digest varchar(64) NOT NULL DEFAULT '',
  last_error_code varchar(64) NOT NULL DEFAULT '',
  last_error_message varchar(255) NOT NULL DEFAULT '',
  requested_at timestamp NOT NULL,
  success_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recovery_claim_token varchar(36) DEFAULT NULL,
  recovery_claimed_at timestamp NULL DEFAULT NULL,
  recovery_attempts int NOT NULL DEFAULT '0',
  next_recovery_at timestamp NULL DEFAULT NULL,
  failed_at timestamp NULL DEFAULT NULL,
  notification_route_token varchar(32) NOT NULL,
  provider_reason varchar(80) DEFAULT NULL,
  restock_required BOOLEAN NOT NULL DEFAULT FALSE,
  restocked_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_refund_order_out_refund_no UNIQUE (out_refund_no),
  CONSTRAINT uk_refund_order_notification_route UNIQUE (notification_route_token),
  INDEX idx_refund_order_after_sale (after_sale_id),
  INDEX idx_refund_order_statistics_success (success_at,status,order_id),
  INDEX idx_refund_order_status_success_at (status,success_at,id),
  INDEX idx_refund_order_recovery (status,next_recovery_at,id),
  INDEX idx_refund_order_status_failed (status,failed_at,id),
  INDEX idx_refund_order_order (order_id,id),
  INDEX idx_refund_order_reconciliation_requested (requested_at,payment_order_id,id),
  INDEX idx_refund_order_reconciliation_payment (payment_order_id,id),
  INDEX idx_refund_order_reconciliation_refund_id (refund_id,id),
  CONSTRAINT chk_refund_order_notification_route CHECK (char_length(notification_route_token) = 32)
);
