-- Shop schema generation 2 baseline.
-- Shipments, waybills, tracking, WeChat platform, and service cards.

CREATE TABLE order_electronic_waybill (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  attempt_no int NOT NULL,
  idempotency_key varchar(64) NOT NULL,
  request_digest char(64) NOT NULL,
  provider_order_id varchar(128) NOT NULL,
  mode varchar(16) NOT NULL,
  delivery_id varchar(128) NOT NULL,
  delivery_name varchar(128) NOT NULL,
  biz_id varchar(128) NOT NULL DEFAULT '',
  service_type int NOT NULL DEFAULT '0',
  service_name varchar(128) NOT NULL DEFAULT '',
  status varchar(16) NOT NULL,
  pending_operation varchar(16) NOT NULL DEFAULT 'NONE',
  waybill_id varchar(128) NOT NULL DEFAULT '',
  parcel_count int NOT NULL DEFAULT '1',
  weight_kg decimal(10,3) NOT NULL,
  length_cm decimal(10,2) NOT NULL,
  width_cm decimal(10,2) NOT NULL,
  height_cm decimal(10,2) NOT NULL,
  custom_remark varchar(1024) NOT NULL DEFAULT '',
  expected_pickup_time bigint DEFAULT NULL,
  sender_name varchar(64) NOT NULL,
  sender_mobile varchar(32) NOT NULL,
  sender_company varchar(128) NOT NULL DEFAULT '',
  sender_province varchar(64) NOT NULL,
  sender_city varchar(64) NOT NULL,
  sender_district varchar(64) NOT NULL,
  sender_detail_address varchar(512) NOT NULL,
  receiver_name varchar(64) NOT NULL,
  receiver_phone varchar(32) NOT NULL,
  receiver_province varchar(64) NOT NULL,
  receiver_city varchar(64) NOT NULL,
  receiver_district varchar(64) NOT NULL,
  receiver_detail_address varchar(512) NOT NULL,
  receiver_location_name varchar(128) NOT NULL DEFAULT '',
  receiver_doorplate varchar(128) NOT NULL DEFAULT '',
  payment_order_id bigint NOT NULL,
  payer_openid varchar(128) NOT NULL,
  last_error_code varchar(64) NOT NULL DEFAULT '',
  last_error_message varchar(255) NOT NULL DEFAULT '',
  upstream_attempt_count int NOT NULL DEFAULT '0',
  last_attempt_at timestamp NULL DEFAULT NULL,
  print_request_count int NOT NULL DEFAULT '0',
  last_print_requested_at timestamp NULL DEFAULT NULL,
  created_by bigint NOT NULL,
  confirmed_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  canceled_at timestamp NULL DEFAULT NULL,
  confirmed_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_electronic_waybill_provider_order UNIQUE (provider_order_id),
  CONSTRAINT uk_order_electronic_waybill_attempt UNIQUE (order_id,attempt_no),
  CONSTRAINT uk_order_electronic_waybill_idempotency UNIQUE (order_id,idempotency_key),
  INDEX idx_order_electronic_waybill_order_status (order_id,status,id),
  INDEX idx_order_electronic_waybill_status_attempt (status,last_attempt_at,id),
  CONSTRAINT chk_order_electronic_waybill_attempt CHECK ((attempt_no > 0)),
  CONSTRAINT chk_order_electronic_waybill_counts CHECK (((upstream_attempt_count >= 0) and (print_request_count >= 0))),
  CONSTRAINT chk_order_electronic_waybill_mode CHECK ((mode in ('SANDBOX','PRODUCTION'))),
  CONSTRAINT chk_order_electronic_waybill_parcel CHECK (((parcel_count = 1) and (weight_kg > 0) and (length_cm > 0) and (width_cm > 0) and (height_cm > 0))),
  CONSTRAINT chk_order_electronic_waybill_pending_operation CHECK ((pending_operation in ('NONE','CREATE','CANCEL','REFRESH'))),
  CONSTRAINT chk_order_electronic_waybill_service_type CHECK ((service_type >= 0)),
  CONSTRAINT chk_order_electronic_waybill_status CHECK ((status in ('CREATING','CREATED','CANCELING','CANCELED','UNKNOWN','FAILED','CONFIRMED')))
);

CREATE TABLE order_electronic_waybill_item (
  id bigint NOT NULL AUTO_INCREMENT,
  electronic_waybill_id bigint NOT NULL,
  order_item_id bigint NOT NULL,
  quantity int NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_electronic_waybill_item UNIQUE (electronic_waybill_id,order_item_id),
  INDEX idx_order_electronic_waybill_item_order_item (order_item_id,electronic_waybill_id),
  CONSTRAINT chk_order_electronic_waybill_item_quantity CHECK ((quantity > 0))
);

CREATE TABLE order_shipment (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  express_company_name varchar(128) DEFAULT NULL,
  tracking_no varchar(80) DEFAULT NULL,
  shipment_note varchar(255) NOT NULL DEFAULT '',
  status varchar(20) NOT NULL,
  wechat_upload_status varchar(20) NOT NULL,
  wechat_error_code varchar(64) NOT NULL DEFAULT '',
  wechat_error_message varchar(255) NOT NULL DEFAULT '',
  retry_count int NOT NULL DEFAULT '0',
  shipped_at timestamp NULL DEFAULT NULL,
  wechat_uploaded_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  logistics_type int NOT NULL DEFAULT '1',
  delivery_mode int NOT NULL DEFAULT '1',
  item_desc varchar(240) NOT NULL DEFAULT '历史订单商品',
  express_company_code varchar(128) DEFAULT NULL,
  consignor_contact varchar(128) DEFAULT NULL,
  receiver_contact varchar(128) DEFAULT NULL,
  upload_time varchar(64) DEFAULT NULL,
  last_attempt_at timestamp NULL DEFAULT NULL,
  wechat_provider_mode varchar(16) NOT NULL DEFAULT 'UNKNOWN',
  wechat_receipt_claim_token varchar(36) DEFAULT NULL,
  wechat_receipt_claimed_at timestamp NULL DEFAULT NULL,
  wechat_receipt_last_checked_at timestamp NULL DEFAULT NULL,
  wechat_receipt_order_state int DEFAULT NULL,
  wechat_receipt_last_error_code varchar(64) NOT NULL DEFAULT '',
  shipment_source varchar(32) NOT NULL DEFAULT 'MANUAL',
  electronic_waybill_id bigint DEFAULT NULL,
  wechat_upload_claim_token varchar(36) DEFAULT NULL,
  wechat_upload_claimed_at timestamp NULL DEFAULT NULL,
  wechat_upload_next_action_at timestamp NULL DEFAULT NULL,
  wechat_upload_attempt_count int NOT NULL DEFAULT '0',
  wechat_upload_not_uploaded_observations int NOT NULL DEFAULT '0',
  wechat_upload_last_reconciled_at timestamp NULL DEFAULT NULL,
  package_no int NOT NULL DEFAULT '1',
  final_shipment BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_shipment_package UNIQUE (order_id,package_no),
  CONSTRAINT uk_order_shipment_electronic_waybill UNIQUE (electronic_waybill_id),
  INDEX idx_order_shipment_wechat_status (wechat_upload_status,retry_count),
  INDEX idx_order_shipment_admin_tracking_no (tracking_no),
  INDEX idx_order_shipment_statistics_shipped (shipped_at,wechat_upload_status,order_id),
  INDEX idx_order_shipment_receipt_reconciliation (wechat_upload_status,wechat_receipt_last_checked_at),
  INDEX idx_order_shipment_wechat_delivery_due (wechat_upload_status,wechat_upload_next_action_at,id),
  INDEX idx_order_shipment_order (order_id,id),
  CONSTRAINT chk_order_shipment_source CHECK ((shipment_source in ('MANUAL','WECHAT_WAYBILL')))
);

CREATE TABLE order_shipment_item (
  id bigint NOT NULL AUTO_INCREMENT,
  shipment_id bigint NOT NULL,
  order_item_id bigint NOT NULL,
  quantity int NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_shipment_item UNIQUE (shipment_id,order_item_id),
  INDEX idx_order_shipment_item_order_item (order_item_id,shipment_id),
  CONSTRAINT chk_order_shipment_item_quantity CHECK ((quantity > 0))
);

CREATE TABLE shipment_tracking_event (
  id bigint NOT NULL AUTO_INCREMENT,
  shipment_id bigint NOT NULL,
  action_time bigint NOT NULL,
  action_type int NOT NULL,
  action_message varchar(512) NOT NULL,
  message_digest char(64) NOT NULL,
  display_order int NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_shipment_tracking_event_identity UNIQUE (shipment_id,action_time,action_type,message_digest),
  INDEX idx_shipment_tracking_event_display (shipment_id,display_order,id),
  CONSTRAINT chk_shipment_tracking_event_order CHECK ((display_order >= 0)),
  CONSTRAINT chk_shipment_tracking_event_time CHECK ((action_time > 0))
);

CREATE TABLE shipment_tracking_snapshot (
  shipment_id bigint NOT NULL,
  query_supported BOOLEAN NOT NULL DEFAULT FALSE,
  query_sync_status varchar(16) NOT NULL DEFAULT 'NOT_REQUESTED',
  logistics_status int DEFAULT NULL,
  query_error_code varchar(64) NOT NULL DEFAULT '',
  query_error_message varchar(255) NOT NULL DEFAULT '',
  path_supported BOOLEAN NOT NULL DEFAULT FALSE,
  path_sync_status varchar(16) NOT NULL DEFAULT 'NOT_REQUESTED',
  path_error_code varchar(64) NOT NULL DEFAULT '',
  path_error_message varchar(255) NOT NULL DEFAULT '',
  claim_token varchar(36) DEFAULT NULL,
  claimed_at timestamp NULL DEFAULT NULL,
  attempt_count int NOT NULL DEFAULT '0',
  last_attempt_at timestamp NULL DEFAULT NULL,
  last_synced_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (shipment_id),
  INDEX idx_shipment_tracking_claim (claimed_at,shipment_id),
  CONSTRAINT chk_shipment_tracking_attempt CHECK ((attempt_count >= 0)),
  CONSTRAINT chk_shipment_tracking_logistics_status CHECK (((logistics_status is null) or (logistics_status between 0 and 6))),
  CONSTRAINT chk_shipment_tracking_path_status CHECK ((path_sync_status in ('NOT_REQUESTED','SYNCING','SYNCED','UNSUPPORTED','FAILED','UNKNOWN','UNAVAILABLE'))),
  CONSTRAINT chk_shipment_tracking_query_status CHECK ((query_sync_status in ('NOT_REQUESTED','SYNCING','SYNCED','UNSUPPORTED','FAILED','UNKNOWN','UNAVAILABLE')))
);

CREATE TABLE shipment_waybill_registration (
  id bigint NOT NULL AUTO_INCREMENT,
  shipment_id bigint NOT NULL,
  registration_kind varchar(16) NOT NULL,
  status varchar(16) NOT NULL,
  waybill_token varchar(1024) NOT NULL DEFAULT '',
  last_error_code varchar(64) NOT NULL DEFAULT '',
  last_error_message varchar(255) NOT NULL DEFAULT '',
  claim_token varchar(36) DEFAULT NULL,
  claimed_at timestamp NULL DEFAULT NULL,
  attempt_count int NOT NULL DEFAULT '0',
  last_attempt_at timestamp NULL DEFAULT NULL,
  registered_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_shipment_waybill_registration_shipment UNIQUE (shipment_id),
  INDEX idx_shipment_waybill_registration_status_claim (status,claimed_at,shipment_id),
  CONSTRAINT chk_shipment_waybill_registration_attempt CHECK ((attempt_count >= 0)),
  CONSTRAINT chk_shipment_waybill_registration_kind CHECK ((registration_kind in ('TRACE','FOLLOW'))),
  CONSTRAINT chk_shipment_waybill_registration_status CHECK ((status in ('PENDING','REGISTERING','REGISTERED','FAILED','UNKNOWN','UNAVAILABLE','SKIPPED')))
);

CREATE TABLE wechat_delivery_company (
  delivery_id varchar(128) NOT NULL,
  delivery_name varchar(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  synced_at timestamp NOT NULL,
  PRIMARY KEY (delivery_id),
  INDEX idx_wechat_delivery_company_enabled_name (enabled,delivery_name)
);

CREATE TABLE wechat_express_setting (
  id bigint NOT NULL,
  mode varchar(16) NOT NULL DEFAULT 'DISABLED',
  message_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sender_name varchar(64) NOT NULL DEFAULT '',
  sender_mobile varchar(32) NOT NULL DEFAULT '',
  sender_company varchar(128) NOT NULL DEFAULT '',
  sender_province varchar(64) NOT NULL DEFAULT '',
  sender_city varchar(64) NOT NULL DEFAULT '',
  sender_district varchar(64) NOT NULL DEFAULT '',
  sender_detail_address varchar(512) NOT NULL DEFAULT '',
  delivery_id varchar(128) NOT NULL DEFAULT '',
  delivery_name varchar(128) NOT NULL DEFAULT '',
  biz_id varchar(128) NOT NULL DEFAULT '',
  service_type int,
  service_name varchar(128) NOT NULL DEFAULT '',
  default_weight_kg decimal(10,3) NOT NULL DEFAULT '1.000',
  default_length_cm decimal(10,2) NOT NULL DEFAULT '20.00',
  default_width_cm decimal(10,2) NOT NULL DEFAULT '15.00',
  default_height_cm decimal(10,2) NOT NULL DEFAULT '10.00',
  revision bigint NOT NULL DEFAULT '0',
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_wechat_express_setting_mode CHECK ((mode in ('DISABLED','SANDBOX','PRODUCTION'))),
  CONSTRAINT chk_wechat_express_setting_parcel CHECK (((default_weight_kg > 0) and (default_length_cm > 0) and (default_width_cm > 0) and (default_height_cm > 0))),
  CONSTRAINT chk_wechat_express_setting_revision CHECK ((revision >= 0)),
  CONSTRAINT chk_wechat_express_setting_service_type CHECK ((service_type >= 0)),
  CONSTRAINT chk_wechat_express_setting_singleton CHECK ((id = 1))
);

CREATE TABLE wechat_platform_config (
  id bigint NOT NULL,
  app_id varchar(64) NOT NULL,
  app_secret_ciphertext varchar(1000) NOT NULL,
  secret_cipher_version int NOT NULL,
  secret_key_id varchar(64) NOT NULL DEFAULT '',
  secret_revision bigint NOT NULL,
  revision bigint NOT NULL,
  created_by bigint DEFAULT NULL,
  updated_by bigint DEFAULT NULL,
  secret_reencrypted_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_wechat_platform_config_app_id CHECK ((app_id <> '')),
  CONSTRAINT chk_wechat_platform_config_cipher_version CHECK (secret_cipher_version = 2),
  CONSTRAINT chk_wechat_platform_config_key_id CHECK (secret_key_id <> ''),
  CONSTRAINT chk_wechat_platform_config_revision CHECK ((revision >= 1)),
  CONSTRAINT chk_wechat_platform_config_secret CHECK ((app_secret_ciphertext <> '')),
  CONSTRAINT chk_wechat_platform_config_secret_revision CHECK ((secret_revision >= 1)),
  CONSTRAINT chk_wechat_platform_config_singleton CHECK ((id = 1))
);

CREATE TABLE wechat_service_card_config (
  id bigint NOT NULL,
  account_template_record_id varchar(128) NOT NULL,
  fallback_product_image varchar(2048) NOT NULL,
  allowed_image_hosts varchar(2048) NOT NULL,
  prefer_order_snapshot_images BOOLEAN NOT NULL,
  callback_enabled BOOLEAN NOT NULL,
  callback_token_ciphertext varchar(1000) DEFAULT NULL,
  callback_token_cipher_version int DEFAULT NULL,
  callback_token_key_id varchar(64) DEFAULT NULL,
  callback_token_secret_revision bigint NOT NULL DEFAULT '0',
  callback_aes_key_ciphertext varchar(1000) DEFAULT NULL,
  callback_aes_key_cipher_version int DEFAULT NULL,
  callback_aes_key_key_id varchar(64) DEFAULT NULL,
  callback_aes_key_secret_revision bigint NOT NULL DEFAULT '0',
  revision bigint NOT NULL,
  created_by bigint DEFAULT NULL,
  updated_by bigint DEFAULT NULL,
  callback_token_reencrypted_at timestamp NULL DEFAULT NULL,
  callback_aes_key_reencrypted_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_wechat_service_card_config_aes_envelope CHECK (((callback_aes_key_ciphertext IS NULL) AND (callback_aes_key_cipher_version IS NULL) AND (callback_aes_key_key_id IS NULL) AND (callback_aes_key_secret_revision = 0)) OR ((callback_aes_key_ciphertext IS NOT NULL) AND (callback_aes_key_cipher_version = 2) AND (callback_aes_key_key_id <> '') AND (callback_aes_key_secret_revision >= 1))),
  CONSTRAINT chk_wechat_service_card_config_aes_revision CHECK ((callback_aes_key_secret_revision >= 0)),
  CONSTRAINT chk_wechat_service_card_config_callback CHECK (((callback_enabled = false) or ((callback_token_ciphertext is not null) and (callback_aes_key_ciphertext is not null)))),
  CONSTRAINT chk_wechat_service_card_config_hosts CHECK ((allowed_image_hosts <> '')),
  CONSTRAINT chk_wechat_service_card_config_image CHECK ((fallback_product_image <> '')),
  CONSTRAINT chk_wechat_service_card_config_revision CHECK ((revision >= 1)),
  CONSTRAINT chk_wechat_service_card_config_singleton CHECK ((id = 1)),
  CONSTRAINT chk_wechat_service_card_config_template CHECK ((account_template_record_id <> '')),
  CONSTRAINT chk_wechat_service_card_config_token_envelope CHECK (((callback_token_ciphertext IS NULL) AND (callback_token_cipher_version IS NULL) AND (callback_token_key_id IS NULL) AND (callback_token_secret_revision = 0)) OR ((callback_token_ciphertext IS NOT NULL) AND (callback_token_cipher_version = 2) AND (callback_token_key_id <> '') AND (callback_token_secret_revision >= 1))),
  CONSTRAINT chk_wechat_service_card_config_token_revision CHECK ((callback_token_secret_revision >= 0))
);

CREATE TABLE wechat_service_card_config_audit (
  id bigint NOT NULL AUTO_INCREMENT,
  revision bigint NOT NULL,
  action_type varchar(24) NOT NULL,
  template_record_id_before varchar(128) NOT NULL,
  template_record_id_after varchar(128) NOT NULL,
  fallback_image_before varchar(2048) NOT NULL,
  fallback_image_after varchar(2048) NOT NULL,
  allowed_hosts_before varchar(2048) NOT NULL,
  allowed_hosts_after varchar(2048) NOT NULL,
  prefer_snapshot_before BOOLEAN NOT NULL,
  prefer_snapshot_after BOOLEAN NOT NULL,
  callback_enabled_before BOOLEAN NOT NULL,
  callback_enabled_after BOOLEAN NOT NULL,
  callback_token_configured_before BOOLEAN NOT NULL,
  callback_token_configured_after BOOLEAN NOT NULL,
  callback_aes_key_configured_before BOOLEAN NOT NULL,
  callback_aes_key_configured_after BOOLEAN NOT NULL,
  operator_id bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_service_card_config_audit_revision UNIQUE (revision),
  INDEX idx_wechat_service_card_config_audit_time (created_at,id),
  CONSTRAINT chk_wechat_service_card_config_audit_action CHECK ((action_type in ('CREATE','UPDATE'))),
  CONSTRAINT chk_wechat_service_card_config_audit_revision CHECK ((revision >= 1))
);

CREATE TABLE wechat_service_card_runtime_audit (
  id bigint NOT NULL AUTO_INCREMENT,
  revision bigint NOT NULL,
  capture_enabled_before BOOLEAN NOT NULL,
  worker_enabled_before BOOLEAN NOT NULL,
  capture_enabled_after BOOLEAN NOT NULL,
  worker_enabled_after BOOLEAN NOT NULL,
  change_reason varchar(200) NOT NULL,
  operator_id bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_service_card_runtime_audit_revision UNIQUE (revision),
  INDEX idx_wechat_service_card_runtime_audit_time (created_at,id),
  CONSTRAINT chk_wechat_service_card_runtime_audit_after CHECK (((worker_enabled_after = false) or (capture_enabled_after = true))),
  CONSTRAINT chk_wechat_service_card_runtime_audit_before CHECK (((worker_enabled_before = false) or (capture_enabled_before = true))),
  CONSTRAINT chk_wechat_service_card_runtime_audit_revision CHECK ((revision >= 1))
);

CREATE TABLE wechat_service_card_runtime_setting (
  id bigint NOT NULL,
  capture_enabled BOOLEAN NOT NULL,
  worker_enabled BOOLEAN NOT NULL,
  revision bigint NOT NULL,
  change_reason varchar(200) NOT NULL,
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_wechat_service_card_runtime_revision CHECK ((revision >= 1)),
  CONSTRAINT chk_wechat_service_card_runtime_singleton CHECK ((id = 1)),
  CONSTRAINT chk_wechat_service_card_runtime_worker CHECK (((worker_enabled = false) or (capture_enabled = true)))
);

CREATE TABLE wechat_shipping_runtime_audit (
  id bigint NOT NULL AUTO_INCREMENT,
  revision bigint NOT NULL,
  upload_enabled_before BOOLEAN NOT NULL,
  delivery_enabled_before BOOLEAN NOT NULL,
  receipt_reconciliation_enabled_before BOOLEAN NOT NULL,
  upload_enabled_after BOOLEAN NOT NULL,
  delivery_enabled_after BOOLEAN NOT NULL,
  receipt_reconciliation_enabled_after BOOLEAN NOT NULL,
  change_reason varchar(200) NOT NULL,
  operator_id bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_shipping_runtime_audit_revision UNIQUE (revision),
  INDEX idx_wechat_shipping_runtime_audit_time (created_at,id),
  CONSTRAINT chk_wechat_shipping_runtime_audit_after_delivery CHECK (((delivery_enabled_after = false) or (upload_enabled_after = true))),
  CONSTRAINT chk_wechat_shipping_runtime_audit_after_receipt CHECK (((receipt_reconciliation_enabled_after = false) or (upload_enabled_after = true))),
  CONSTRAINT chk_wechat_shipping_runtime_audit_before_delivery CHECK (((delivery_enabled_before = false) or (upload_enabled_before = true))),
  CONSTRAINT chk_wechat_shipping_runtime_audit_before_receipt CHECK (((receipt_reconciliation_enabled_before = false) or (upload_enabled_before = true))),
  CONSTRAINT chk_wechat_shipping_runtime_audit_revision CHECK ((revision >= 1))
);

CREATE TABLE wechat_shipping_runtime_setting (
  id bigint NOT NULL,
  upload_enabled BOOLEAN NOT NULL,
  delivery_enabled BOOLEAN NOT NULL,
  receipt_reconciliation_enabled BOOLEAN NOT NULL,
  revision bigint NOT NULL,
  change_reason varchar(200) NOT NULL,
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_wechat_shipping_runtime_delivery CHECK (((delivery_enabled = false) or (upload_enabled = true))),
  CONSTRAINT chk_wechat_shipping_runtime_receipt CHECK (((receipt_reconciliation_enabled = false) or (upload_enabled = true))),
  CONSTRAINT chk_wechat_shipping_runtime_revision CHECK ((revision >= 1)),
  CONSTRAINT chk_wechat_shipping_runtime_singleton CHECK ((id = 1))
);

CREATE TABLE wechat_service_card (
  id bigint NOT NULL AUTO_INCREMENT,
  order_id bigint NOT NULL,
  payment_order_id bigint NOT NULL,
  notify_type int NOT NULL DEFAULT '2001',
  notify_code_digest char(64) NOT NULL,
  account_template_record_id varchar(128) NOT NULL DEFAULT '',
  last_enqueued_status smallint DEFAULT NULL,
  restore_status smallint DEFAULT NULL,
  remote_status smallint DEFAULT NULL,
  remote_code_state smallint DEFAULT NULL,
  remote_code_expire_at timestamp NULL DEFAULT NULL,
  terminal BOOLEAN NOT NULL DEFAULT FALSE,
  send_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  send_block_reason varchar(32) NOT NULL DEFAULT '',
  send_blocked_at timestamp NULL DEFAULT NULL,
  activated_at timestamp NULL DEFAULT NULL,
  version bigint NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_service_card_order UNIQUE (order_id),
  CONSTRAINT uk_wechat_service_card_payment UNIQUE (payment_order_id),
  INDEX idx_wechat_service_card_notify_digest (notify_code_digest,id),
  CONSTRAINT fk_wechat_service_card_order FOREIGN KEY (order_id) REFERENCES shop_order (id),
  CONSTRAINT fk_wechat_service_card_payment FOREIGN KEY (payment_order_id) REFERENCES payment_order (id),
  CONSTRAINT chk_wechat_service_card_notify_type CHECK ((notify_type = 2001)),
  CONSTRAINT chk_wechat_service_card_statuses CHECK ((((last_enqueued_status is null) or (last_enqueued_status between 1 and 11)) and ((restore_status is null) or (restore_status in (2,4,6))) and ((remote_status is null) or (remote_status between 1 and 11)) and ((remote_code_state is null) or (remote_code_state in (0,1,2,10))) and (((send_blocked = false) and (send_block_reason = '') and (send_blocked_at is null)) or ((send_blocked = true) and (send_block_reason = 'USER_REFUSED') and (send_blocked_at is not null)))))
);

CREATE TABLE wechat_service_card_delivery (
  id bigint NOT NULL AUTO_INCREMENT,
  card_id bigint NOT NULL,
  sequence_no int NOT NULL,
  target_status smallint NOT NULL,
  content_json text NOT NULL,
  check_json text,
  state varchar(20) NOT NULL DEFAULT 'PENDING',
  attempt_count int NOT NULL DEFAULT '0',
  reconcile_attempt_count int NOT NULL DEFAULT '0',
  claim_token varchar(36) DEFAULT NULL,
  claimed_at timestamp NULL DEFAULT NULL,
  next_action_at timestamp NULL DEFAULT NULL,
  not_applied_observations int NOT NULL DEFAULT '0',
  last_reconciled_at timestamp NULL DEFAULT NULL,
  provider_error_code varchar(64) NOT NULL DEFAULT '',
  provider_error_message varchar(255) NOT NULL DEFAULT '',
  applied_at timestamp NULL DEFAULT NULL,
  message_result_state varchar(20) NOT NULL DEFAULT 'UNKNOWN',
  message_fail_ret int DEFAULT NULL,
  message_fail_message varchar(255) NOT NULL DEFAULT '',
  message_result_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_service_card_delivery_sequence UNIQUE (card_id,sequence_no),
  CONSTRAINT uk_wechat_service_card_delivery_id_card UNIQUE (id,card_id),
  INDEX idx_wechat_service_card_delivery_due (state,next_action_at,id),
  INDEX idx_wechat_service_card_delivery_card_state (card_id,state,sequence_no),
  CONSTRAINT fk_wechat_service_card_delivery_card FOREIGN KEY (card_id) REFERENCES wechat_service_card (id),
  CONSTRAINT chk_wechat_service_card_delivery_attempts CHECK (((attempt_count >= 0) and (reconcile_attempt_count >= 0) and (not_applied_observations >= 0))),
  CONSTRAINT chk_wechat_service_card_delivery_claim CHECK ((((state in ('SENDING','RECONCILING')) and (claim_token is not null) and (claimed_at is not null)) or ((state not in ('SENDING','RECONCILING')) and (claim_token is null) and (claimed_at is null)))),
  CONSTRAINT chk_wechat_service_card_delivery_sequence CHECK ((sequence_no > 0)),
  CONSTRAINT chk_wechat_service_card_delivery_state CHECK (((state in ('PENDING','SENDING','UNKNOWN','RECONCILING','SUCCEEDED','FAILED','SKIPPED')) and (target_status between 1 and 11) and (message_result_state in ('UNKNOWN','FAILED')) and (((message_result_state = 'UNKNOWN') and (message_fail_ret is null) and (message_result_at is null)) or ((message_result_state = 'FAILED') and (message_fail_ret < 0) and (message_result_at is not null)))))
);

CREATE TABLE wechat_service_card_callback_log (
  id bigint NOT NULL AUTO_INCREMENT,
  event_digest char(64) NOT NULL,
  card_id bigint DEFAULT NULL,
  delivery_id bigint DEFAULT NULL,
  card_status smallint DEFAULT NULL,
  fail_ret int DEFAULT NULL,
  fail_message varchar(255) NOT NULL DEFAULT '',
  matched BOOLEAN NOT NULL DEFAULT FALSE,
  received_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_service_card_callback_digest UNIQUE (event_digest),
  INDEX idx_wechat_service_card_callback_received (received_at,id),
  INDEX fk_wechat_service_card_callback_card (card_id),
  INDEX fk_wechat_service_card_callback_delivery_card (delivery_id,card_id),
  CONSTRAINT fk_wechat_service_card_callback_card FOREIGN KEY (card_id) REFERENCES wechat_service_card (id),
  CONSTRAINT fk_wechat_service_card_callback_delivery_card FOREIGN KEY (delivery_id, card_id) REFERENCES wechat_service_card_delivery (id, card_id),
  CONSTRAINT chk_wechat_service_card_callback_status CHECK ((((card_status is null) or (card_status between 1 and 11)) and ((fail_ret is null) or (fail_ret < 0)) and ((delivery_id is null) or (matched = true)) and ((matched = false) or ((card_id is not null) and (delivery_id is not null)))))
);
