-- Shop schema generation 2 baseline.
-- Customer service, cleanup, finance reconciliation, and compliance.

CREATE TABLE customer_service_agent_profile (
  admin_user_id bigint NOT NULL,
  service_name_override varchar(64) DEFAULT NULL,
  routing_weight int NOT NULL DEFAULT '100',
  last_assigned_at timestamp NULL DEFAULT NULL,
  updated_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  auto_accept_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  auto_accept_below int NOT NULL DEFAULT '5',
  auto_accept_count int NOT NULL DEFAULT '1',
  bound_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  welcome_message varchar(2000) NOT NULL DEFAULT '',
  PRIMARY KEY (admin_user_id),
  CONSTRAINT chk_customer_service_auto_accept_below CHECK (((auto_accept_below >= 1) and (auto_accept_below <= 1000))),
  CONSTRAINT chk_customer_service_auto_accept_count CHECK (((auto_accept_count >= 1) and (auto_accept_count <= 1000))),
  CONSTRAINT chk_customer_service_routing_weight CHECK (((routing_weight >= 1) and (routing_weight <= 1000)))
);

CREATE TABLE customer_service_agent_state (
  admin_user_id bigint NOT NULL,
  work_status varchar(20) NOT NULL DEFAULT 'BUSY',
  max_active_conversations int DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (admin_user_id),
  CONSTRAINT chk_customer_service_max_active_conversations CHECK (((max_active_conversations is null) or ((max_active_conversations >= 1) and (max_active_conversations <= 1000))))
);

CREATE TABLE customer_service_assignment_log (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id bigint NOT NULL,
  action varchar(20) NOT NULL,
  from_admin_user_id bigint DEFAULT NULL,
  to_admin_user_id bigint DEFAULT NULL,
  operator_type varchar(20) NOT NULL,
  operator_id bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_customer_service_assignment_conversation (conversation_id,id),
  INDEX idx_customer_service_assignment_action_created (conversation_id,action,created_at,id)
);

CREATE TABLE customer_service_auto_reply_config (
  id bigint NOT NULL,
  revision bigint NOT NULL DEFAULT '0',
  opening_message varchar(2000) NOT NULL DEFAULT '',
  offline_message varchar(2000) NOT NULL DEFAULT '',
  updated_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_customer_service_auto_reply_config_singleton CHECK ((id = 1)),
  CONSTRAINT chk_customer_service_auto_reply_revision CHECK ((revision >= 0))
);

CREATE TABLE customer_service_common_question (
  id bigint NOT NULL AUTO_INCREMENT,
  question varchar(200) NOT NULL,
  answer varchar(2000) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order int NOT NULL DEFAULT '0',
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_customer_service_common_question_order (enabled,sort_order,id),
  CONSTRAINT chk_customer_service_common_question_sort CHECK ((sort_order >= 0))
);

CREATE TABLE customer_service_config (
  id bigint NOT NULL,
  default_service_name varchar(64) NOT NULL,
  avatar varchar(500) NOT NULL DEFAULT '',
  auto_assign_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  assignment_strategy varchar(32) NOT NULL DEFAULT 'LEAST_LOADED',
  sticky_agent_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sticky_window_hours int NOT NULL DEFAULT '48',
  updated_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  avatar_file_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT chk_customer_service_config_singleton CHECK ((id = 1)),
  CONSTRAINT chk_customer_service_sticky_window CHECK (((sticky_window_hours >= 1) and (sticky_window_hours <= 720)))
);

CREATE TABLE customer_service_consultation_resource (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id bigint NOT NULL,
  consultation_no int NOT NULL,
  resource_type varchar(20) NOT NULL,
  resource_id bigint NOT NULL,
  added_by_type varchar(20) NOT NULL,
  added_by_id bigint NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_service_consultation_resource UNIQUE (conversation_id,consultation_no,resource_type,resource_id),
  INDEX idx_customer_service_consultation_resource_lookup (resource_type,resource_id,conversation_id)
);

CREATE TABLE customer_service_conversation (
  id bigint NOT NULL AUTO_INCREMENT,
  app_user_id bigint NOT NULL,
  status varchar(20) NOT NULL,
  assigned_admin_user_id bigint DEFAULT NULL,
  last_message_at timestamp NULL DEFAULT NULL,
  app_unread_count int NOT NULL DEFAULT '0',
  admin_unread_count int NOT NULL DEFAULT '0',
  claimed_at timestamp NULL DEFAULT NULL,
  closed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consultation_no int NOT NULL DEFAULT '1',
  context_type varchar(20) NOT NULL DEFAULT 'GENERAL',
  context_id bigint DEFAULT NULL,
  activated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_service_conversation_user UNIQUE (app_user_id),
  INDEX idx_customer_service_conversation_queue (status,last_message_at,id),
  INDEX idx_customer_service_statistics_activated (activated_at,status,id),
  INDEX idx_customer_service_conversation_agent_active (assigned_admin_user_id,status,id),
  INDEX idx_customer_service_conversation_context (context_type,context_id,id)
);

CREATE TABLE customer_service_conversation_order (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id bigint NOT NULL,
  order_id bigint NOT NULL,
  linked_by_type varchar(20) NOT NULL,
  linked_by_id bigint NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_service_conversation_order UNIQUE (conversation_id,order_id),
  INDEX idx_customer_service_conversation_order_order (order_id,conversation_id)
);

CREATE TABLE customer_service_message (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id bigint NOT NULL,
  sender_type varchar(20) NOT NULL,
  sender_id bigint DEFAULT NULL,
  message_type varchar(20) NOT NULL,
  content varchar(2000) NOT NULL,
  client_message_id varchar(64) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consultation_no int NOT NULL DEFAULT '1',
  resource_id bigint DEFAULT NULL,
  automation_key varchar(128) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_service_message_client UNIQUE (conversation_id,sender_type,sender_id,client_message_id),
  CONSTRAINT uk_customer_service_message_automation UNIQUE (conversation_id,consultation_no,automation_key),
  INDEX idx_customer_service_message_conversation (conversation_id,id),
  INDEX idx_customer_service_message_consultation_created (conversation_id,consultation_no,created_at,sender_type),
  INDEX idx_customer_service_message_retention (created_at,id),
  INDEX idx_customer_service_message_order_resource (message_type,resource_id,conversation_id,id)
);

CREATE TABLE customer_service_offline_reply_state (
  app_user_id bigint NOT NULL,
  last_replied_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (app_user_id)
);

CREATE TABLE customer_service_quick_reply (
  id bigint NOT NULL AUTO_INCREMENT,
  group_id bigint NOT NULL,
  content varchar(2000) NOT NULL,
  sort_order int NOT NULL DEFAULT '0',
  created_by bigint DEFAULT NULL,
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_customer_service_quick_reply_group_order (group_id,sort_order,id),
  CONSTRAINT chk_customer_service_quick_reply_sort CHECK ((sort_order >= 0))
);

CREATE TABLE customer_service_quick_reply_group (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(64) NOT NULL,
  sort_order int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_customer_service_quick_reply_group_sort CHECK ((sort_order >= 0))
);

CREATE TABLE customer_service_smart_reply_group (
  id bigint NOT NULL AUTO_INCREMENT,
  name varchar(64) NOT NULL,
  reply_content varchar(2000) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order int NOT NULL DEFAULT '0',
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_customer_service_smart_reply_group_order (enabled,sort_order,id),
  CONSTRAINT chk_customer_service_smart_reply_sort CHECK ((sort_order >= 0))
);

CREATE TABLE customer_service_smart_reply_question (
  id bigint NOT NULL AUTO_INCREMENT,
  reply_group_id bigint NOT NULL,
  question varchar(200) NOT NULL,
  normalized_question varchar(200) NOT NULL,
  sort_order int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_customer_service_smart_reply_question_group (reply_group_id,sort_order,id),
  INDEX idx_customer_service_smart_reply_question_normalized (normalized_question),
  CONSTRAINT chk_customer_service_smart_reply_question_sort CHECK ((sort_order >= 0))
);

CREATE TABLE customer_service_transfer_request (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id bigint NOT NULL,
  from_admin_user_id bigint NOT NULL,
  to_admin_user_id bigint NOT NULL,
  status varchar(20) NOT NULL,
  reason_code varchar(40) NOT NULL,
  reason_note varchar(200) DEFAULT NULL,
  pending_key int DEFAULT NULL,
  expires_at timestamp NOT NULL,
  resolved_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_service_transfer_pending UNIQUE (conversation_id,pending_key),
  INDEX idx_customer_service_transfer_target (to_admin_user_id,status,expires_at,id)
);

CREATE TABLE data_cleanup_config (
  id bigint NOT NULL,
  revision bigint NOT NULL DEFAULT '0',
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_data_cleanup_config_revision CHECK ((revision >= 0)),
  CONSTRAINT chk_data_cleanup_config_singleton CHECK ((id = 1))
);

CREATE TABLE data_cleanup_task_setting (
  task_code varchar(40) NOT NULL,
  enabled BOOLEAN NOT NULL,
  retention_days int DEFAULT NULL,
  batch_size int NOT NULL,
  cron_expression varchar(80) NOT NULL,
  zone_id varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
  batch_interval_seconds int NOT NULL DEFAULT '60',
  upload_pending_grace_minutes int DEFAULT NULL,
  config_revision bigint NOT NULL DEFAULT '0',
  run_sequence bigint NOT NULL DEFAULT '0',
  next_run_at timestamp NULL DEFAULT NULL,
  lease_token varchar(36) DEFAULT NULL,
  lease_until timestamp NULL DEFAULT NULL,
  last_started_at timestamp NULL DEFAULT NULL,
  last_completed_at timestamp NULL DEFAULT NULL,
  last_status varchar(16) NOT NULL DEFAULT 'NEVER',
  last_processed_count int NOT NULL DEFAULT '0',
  last_error varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  retain_reviews BOOLEAN DEFAULT NULL,
  PRIMARY KEY (task_code),
  INDEX idx_data_cleanup_task_due (enabled,next_run_at,lease_until),
  CONSTRAINT chk_data_cleanup_batch_interval CHECK ((batch_interval_seconds between 60 and 86400)),
  CONSTRAINT chk_data_cleanup_batch_size CHECK ((((task_code in ('ANALYTICS_EVENT','ADMIN_SYSTEM_LOG')) and (batch_size between 1 and 50000)) or ((task_code = 'CUSTOMER_SERVICE_MESSAGE') and (batch_size between 1 and 10000)) or ((task_code = 'ORDER_AGGREGATE') and (batch_size between 1 and 100)) or ((task_code in ('STORAGE_ASSET','DIRECT_UPLOAD_SESSION')) and (batch_size between 1 and 1000)))),
  CONSTRAINT chk_data_cleanup_last_count CHECK ((last_processed_count >= 0)),
  CONSTRAINT chk_data_cleanup_last_status CHECK ((last_status in ('NEVER','RUNNING','SUCCESS','FAILED'))),
  CONSTRAINT chk_data_cleanup_retain_reviews CHECK ((((task_code = 'ORDER_AGGREGATE') and (retain_reviews is not null)) or ((task_code <> 'ORDER_AGGREGATE') and (retain_reviews is null)))),
  CONSTRAINT chk_data_cleanup_retention_days CHECK ((((task_code = 'ANALYTICS_EVENT') and (retention_days is not null) and (retention_days between 367 and 3650)) or ((task_code in ('ADMIN_SYSTEM_LOG','CUSTOMER_SERVICE_MESSAGE')) and (retention_days is not null) and (retention_days between 1 and 3650)) or ((task_code = 'ORDER_AGGREGATE') and (retention_days is not null) and (retention_days between 1095 and 3650)) or ((task_code = 'DIRECT_UPLOAD_SESSION') and (retention_days is not null) and (retention_days between 1 and 365)) or ((task_code = 'STORAGE_ASSET') and (retention_days is null)))),
  CONSTRAINT chk_data_cleanup_run_sequence CHECK ((run_sequence >= 0)),
  CONSTRAINT chk_data_cleanup_task_code CHECK ((task_code in ('ANALYTICS_EVENT','ADMIN_SYSTEM_LOG','CUSTOMER_SERVICE_MESSAGE','ORDER_AGGREGATE','STORAGE_ASSET','DIRECT_UPLOAD_SESSION'))),
  CONSTRAINT chk_data_cleanup_task_revision CHECK ((config_revision >= 0)),
  CONSTRAINT chk_data_cleanup_upload_grace CHECK ((((task_code = 'STORAGE_ASSET') and (upload_pending_grace_minutes is not null) and (upload_pending_grace_minutes between 5 and 10080)) or ((task_code <> 'STORAGE_ASSET') and (upload_pending_grace_minutes is null))))
);

CREATE TABLE finance_reconciliation_batch (
  id bigint NOT NULL AUTO_INCREMENT,
  mch_id varchar(32) NOT NULL,
  bill_date date NOT NULL,
  bill_type varchar(24) NOT NULL DEFAULT 'TRADE_ALL',
  credential_config_id bigint DEFAULT NULL,
  credential_fingerprint char(64) NOT NULL DEFAULT '',
  status varchar(24) NOT NULL,
  phase varchar(24) NOT NULL DEFAULT 'QUEUED',
  provider_hash_verified BOOLEAN NOT NULL DEFAULT FALSE,
  content_sha256 char(64) NOT NULL DEFAULT '',
  storage_provider varchar(32) NOT NULL DEFAULT '',
  storage_container varchar(128) NOT NULL DEFAULT '',
  storage_region varchar(64) NOT NULL DEFAULT '',
  object_key varchar(512) NOT NULL DEFAULT '',
  content_type varchar(128) NOT NULL DEFAULT '',
  source_size_bytes bigint NOT NULL DEFAULT '0',
  total_rows bigint NOT NULL DEFAULT '0',
  payment_rows bigint NOT NULL DEFAULT '0',
  refund_rows bigint NOT NULL DEFAULT '0',
  channel_payment_amount_cent bigint NOT NULL DEFAULT '0',
  channel_refund_amount_cent bigint NOT NULL DEFAULT '0',
  local_payment_amount_cent bigint NOT NULL DEFAULT '0',
  local_refund_amount_cent bigint NOT NULL DEFAULT '0',
  difference_count bigint NOT NULL DEFAULT '0',
  open_difference_count bigint NOT NULL DEFAULT '0',
  claim_token varchar(64) DEFAULT NULL,
  claimed_at timestamp NULL DEFAULT NULL,
  attempt_count int NOT NULL DEFAULT '0',
  next_attempt_at timestamp NULL DEFAULT NULL,
  last_error_code varchar(64) NOT NULL DEFAULT '',
  last_error_message varchar(255) NOT NULL DEFAULT '',
  requested_by bigint DEFAULT NULL,
  requested_at timestamp NOT NULL,
  started_at timestamp NULL DEFAULT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  version bigint NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_finance_reconciliation_batch UNIQUE (mch_id,bill_date,bill_type),
  INDEX idx_finance_reconciliation_batch_schedule (status,next_attempt_at,claimed_at,id),
  INDEX idx_finance_reconciliation_batch_date (bill_date,mch_id,id),
  CONSTRAINT chk_finance_reconciliation_batch_bill_type CHECK ((bill_type = 'TRADE_ALL')),
  CONSTRAINT chk_finance_reconciliation_batch_claim CHECK ((((claim_token is null) and (claimed_at is null)) or ((claim_token is not null) and (claimed_at is not null)))),
  CONSTRAINT chk_finance_reconciliation_batch_counts CHECK (((source_size_bytes >= 0) and (total_rows >= 0) and (payment_rows >= 0) and (refund_rows >= 0) and (difference_count >= 0) and (open_difference_count >= 0) and (attempt_count >= 0) and (total_rows = (payment_rows + refund_rows)) and (open_difference_count <= difference_count) and (channel_payment_amount_cent >= 0) and (channel_refund_amount_cent >= 0) and (local_payment_amount_cent >= 0) and (local_refund_amount_cent >= 0))),
  CONSTRAINT chk_finance_reconciliation_batch_phase CHECK ((phase in ('QUEUED','DOWNLOAD','VERIFY','PARSE','STORE','COMPARE','COMPLETE'))),
  CONSTRAINT chk_finance_reconciliation_batch_status CHECK ((status in ('PENDING','RUNNING','RETRY_WAIT','BALANCED','DIFFERENCES','EMPTY','FAILED')))
);

CREATE TABLE finance_reconciliation_runtime_audit (
  id bigint NOT NULL AUTO_INCREMENT,
  revision bigint NOT NULL,
  worker_enabled_before BOOLEAN NOT NULL,
  daily_enabled_before BOOLEAN NOT NULL,
  worker_enabled_after BOOLEAN NOT NULL,
  daily_enabled_after BOOLEAN NOT NULL,
  change_reason varchar(200) NOT NULL,
  operator_id bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_finance_reconciliation_runtime_audit_revision UNIQUE (revision),
  INDEX idx_finance_reconciliation_runtime_audit_time (created_at,id),
  CONSTRAINT chk_finance_reconciliation_runtime_audit_after CHECK (((daily_enabled_after = false) or (worker_enabled_after = true))),
  CONSTRAINT chk_finance_reconciliation_runtime_audit_before CHECK (((daily_enabled_before = false) or (worker_enabled_before = true))),
  CONSTRAINT chk_finance_reconciliation_runtime_audit_revision CHECK ((revision >= 1))
);

CREATE TABLE finance_reconciliation_runtime_setting (
  id bigint NOT NULL,
  worker_enabled BOOLEAN NOT NULL,
  daily_enabled BOOLEAN NOT NULL,
  revision bigint NOT NULL,
  change_reason varchar(200) NOT NULL,
  updated_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT chk_finance_reconciliation_runtime_daily CHECK (((daily_enabled = false) or (worker_enabled = true))),
  CONSTRAINT chk_finance_reconciliation_runtime_revision CHECK ((revision >= 1)),
  CONSTRAINT chk_finance_reconciliation_runtime_singleton CHECK ((id = 1))
);

CREATE TABLE legal_document_revision (
  id bigint NOT NULL AUTO_INCREMENT,
  document_type varchar(32) NOT NULL,
  version varchar(40) NOT NULL,
  title varchar(160) NOT NULL DEFAULT '',
  content mediumtext NOT NULL,
  content_sha256 char(64) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'DRAFT',
  current_publication_key varchar(32) DEFAULT NULL,
  effective_at timestamp NULL DEFAULT NULL,
  created_by bigint NOT NULL,
  published_by bigint DEFAULT NULL,
  published_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_legal_document_version UNIQUE (document_type,version),
  CONSTRAINT uk_legal_document_current UNIQUE (current_publication_key),
  INDEX idx_legal_document_history (document_type,status,id),
  CONSTRAINT chk_legal_document_current CHECK (((current_publication_key is null) or (current_publication_key = document_type))),
  CONSTRAINT chk_legal_document_status CHECK ((status in ('DRAFT','PUBLISHED','SUPERSEDED'))),
  CONSTRAINT chk_legal_document_type CHECK ((document_type in ('PRIVACY_POLICY','USER_AGREEMENT','AFTER_SALE_POLICY','ACCOUNT_CANCELLATION_NOTICE')))
);

CREATE TABLE merchant_publication_revision (
  id bigint NOT NULL AUTO_INCREMENT,
  revision_no bigint NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'DRAFT',
  current_publication_key smallint DEFAULT NULL,
  legal_name varchar(160) NOT NULL DEFAULT '',
  entity_type varchar(32) NOT NULL DEFAULT '',
  unified_social_credit_code varchar(32) NOT NULL DEFAULT '',
  business_address varchar(512) NOT NULL DEFAULT '',
  customer_service_phone varchar(32) NOT NULL DEFAULT '',
  complaint_phone varchar(32) NOT NULL DEFAULT '',
  business_license_asset_id bigint DEFAULT NULL,
  food_qualification_type varchar(40) NOT NULL DEFAULT '',
  food_qualification_number varchar(96) NOT NULL DEFAULT '',
  food_qualification_asset_id bigint DEFAULT NULL,
  food_qualification_valid_from date DEFAULT NULL,
  food_qualification_valid_until date DEFAULT NULL,
  created_by bigint NOT NULL,
  published_by bigint DEFAULT NULL,
  published_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_merchant_publication_revision UNIQUE (revision_no),
  CONSTRAINT uk_merchant_publication_current UNIQUE (current_publication_key),
  INDEX idx_merchant_publication_status_revision (status,revision_no),
  CONSTRAINT chk_merchant_publication_current CHECK (((current_publication_key is null) or (current_publication_key = 1))),
  CONSTRAINT chk_merchant_publication_status CHECK ((status in ('DRAFT','PUBLISHED','SUPERSEDED')))
);

CREATE TABLE order_archive_manifest (
  id bigint NOT NULL AUTO_INCREMENT,
  source_order_id bigint NOT NULL,
  order_no_digest char(64) NOT NULL,
  object_key varchar(255) NOT NULL,
  provider varchar(20) NOT NULL,
  storage_container varchar(500) NOT NULL,
  storage_region varchar(64) NOT NULL,
  content_type varchar(128) NOT NULL DEFAULT 'application/zip',
  sha256 char(64) NOT NULL,
  size_bytes bigint NOT NULL,
  archive_format_version int NOT NULL DEFAULT '1',
  item_count int NOT NULL DEFAULT '0',
  payment_count int NOT NULL DEFAULT '0',
  refund_count int NOT NULL DEFAULT '0',
  after_sale_count int NOT NULL DEFAULT '0',
  status varchar(20) NOT NULL DEFAULT 'PURGED',
  archived_at timestamp NOT NULL,
  purged_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_archive_source UNIQUE (source_order_id),
  CONSTRAINT uk_order_archive_object_key UNIQUE (object_key),
  INDEX idx_order_archive_purged (purged_at,id),
  CONSTRAINT chk_order_archive_counts CHECK (((item_count >= 0) and (payment_count >= 0) and (refund_count >= 0) and (after_sale_count >= 0))),
  CONSTRAINT chk_order_archive_provider CHECK ((provider = 'TENCENT_COS')),
  CONSTRAINT chk_order_archive_size CHECK ((size_bytes >= 0)),
  CONSTRAINT chk_order_archive_status CHECK ((status = 'PURGED'))
);

CREATE TABLE wechat_trade_bill_entry (
  id bigint NOT NULL AUTO_INCREMENT,
  batch_id bigint NOT NULL,
  row_no bigint NOT NULL,
  entry_type varchar(16) NOT NULL,
  transaction_id varchar(64) NOT NULL DEFAULT '',
  out_trade_no varchar(64) NOT NULL DEFAULT '',
  refund_id varchar(64) NOT NULL DEFAULT '',
  out_refund_no varchar(64) NOT NULL DEFAULT '',
  occurred_at timestamp NOT NULL,
  amount_cent bigint NOT NULL,
  currency varchar(16) NOT NULL DEFAULT 'CNY',
  channel_status varchar(32) NOT NULL DEFAULT '',
  row_digest char(64) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_wechat_trade_bill_entry_row UNIQUE (batch_id,row_no),
  INDEX idx_wechat_trade_bill_entry_payment (batch_id,out_trade_no,transaction_id,id),
  INDEX idx_wechat_trade_bill_entry_refund (batch_id,out_refund_no,refund_id,id),
  INDEX idx_wechat_trade_bill_entry_digest (batch_id,row_digest,id),
  CONSTRAINT fk_wechat_trade_bill_entry_batch FOREIGN KEY (batch_id) REFERENCES finance_reconciliation_batch (id) ON DELETE RESTRICT,
  CONSTRAINT chk_wechat_trade_bill_entry_amount CHECK ((amount_cent >= 0)),
  CONSTRAINT chk_wechat_trade_bill_entry_row_no CHECK ((row_no > 0)),
  CONSTRAINT chk_wechat_trade_bill_entry_type CHECK ((entry_type in ('PAYMENT','REFUND')))
);

CREATE TABLE app_user_account_cancellation (
  id bigint NOT NULL,
  user_id bigint NOT NULL,
  legal_document_revision_id bigint NOT NULL,
  notice_version varchar(40) NOT NULL,
  notice_content_sha256 char(64) NOT NULL,
  channel varchar(32) NOT NULL,
  mini_program_env varchar(16) NOT NULL,
  identity_verified_at timestamp NOT NULL,
  deleted_data_categories varchar(1000) NOT NULL,
  retained_data_categories varchar(1000) NOT NULL,
  completed_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_app_user_account_cancellation_user UNIQUE (user_id),
  INDEX fk_account_cancellation_notice (legal_document_revision_id),
  INDEX idx_account_cancellation_completed (completed_at,id),
  CONSTRAINT fk_account_cancellation_notice FOREIGN KEY (legal_document_revision_id) REFERENCES legal_document_revision (id),
  CONSTRAINT fk_account_cancellation_user FOREIGN KEY (user_id) REFERENCES app_user (id),
  CONSTRAINT chk_account_cancellation_channel CHECK ((channel = 'WECHAT_MINIPROGRAM')),
  CONSTRAINT chk_account_cancellation_env CHECK ((mini_program_env in ('develop','trial','release')))
);

CREATE TABLE app_user_document_consent (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  legal_document_revision_id bigint NOT NULL,
  document_type varchar(32) NOT NULL,
  document_version varchar(40) NOT NULL,
  content_sha256 char(64) NOT NULL,
  channel varchar(32) NOT NULL,
  mini_program_env varchar(16) NOT NULL,
  accepted_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_app_user_document_consent_revision UNIQUE (user_id,legal_document_revision_id),
  INDEX fk_app_user_document_consent_revision (legal_document_revision_id),
  INDEX idx_app_user_document_consent_user_time (user_id,accepted_at,id),
  CONSTRAINT fk_app_user_document_consent_revision FOREIGN KEY (legal_document_revision_id) REFERENCES legal_document_revision (id),
  CONSTRAINT fk_app_user_document_consent_user FOREIGN KEY (user_id) REFERENCES app_user (id),
  CONSTRAINT chk_app_user_document_consent_env CHECK ((mini_program_env in ('develop','trial','release'))),
  CONSTRAINT chk_app_user_document_consent_type CHECK ((document_type in ('PRIVACY_POLICY','USER_AGREEMENT','AFTER_SALE_POLICY')))
);

CREATE TABLE purged_order_identity (
  id bigint NOT NULL AUTO_INCREMENT,
  archive_manifest_id bigint NOT NULL,
  user_idempotency_digest char(64) NOT NULL,
  order_no_digest char(64) NOT NULL,
  final_status varchar(20) NOT NULL,
  purged_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_purged_order_idempotency UNIQUE (user_idempotency_digest),
  CONSTRAINT uk_purged_order_no UNIQUE (order_no_digest),
  CONSTRAINT uk_purged_order_archive UNIQUE (archive_manifest_id),
  INDEX idx_purged_order_purged (purged_at,id),
  CONSTRAINT fk_purged_order_archive FOREIGN KEY (archive_manifest_id) REFERENCES order_archive_manifest (id) ON DELETE RESTRICT
);

CREATE TABLE purged_payment_identity (
  id bigint NOT NULL AUTO_INCREMENT,
  archive_manifest_id bigint NOT NULL,
  out_trade_no_digest char(64) NOT NULL,
  transaction_id_digest char(64) NOT NULL DEFAULT '',
  notification_route_digest char(64) NOT NULL,
  payment_config_id bigint NOT NULL,
  payment_config_fingerprint char(64) NOT NULL,
  final_status varchar(32) NOT NULL,
  amount_cent bigint NOT NULL,
  currency varchar(16) NOT NULL,
  purged_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_purged_payment_trade UNIQUE (out_trade_no_digest),
  CONSTRAINT uk_purged_payment_route UNIQUE (notification_route_digest),
  INDEX fk_purged_payment_archive (archive_manifest_id),
  INDEX idx_purged_payment_transaction (transaction_id_digest),
  INDEX idx_purged_payment_config (payment_config_id),
  INDEX idx_purged_payment_purged (purged_at,id),
  CONSTRAINT fk_purged_payment_archive FOREIGN KEY (archive_manifest_id) REFERENCES order_archive_manifest (id) ON DELETE RESTRICT,
  CONSTRAINT chk_purged_payment_amount CHECK ((amount_cent > 0)),
  CONSTRAINT chk_purged_payment_config_fingerprint CHECK (char_length(payment_config_fingerprint) = 64),
  CONSTRAINT chk_purged_payment_notification_route CHECK (char_length(notification_route_digest) = 64)
);

CREATE TABLE purged_refund_identity (
  id bigint NOT NULL AUTO_INCREMENT,
  archive_manifest_id bigint NOT NULL,
  out_refund_no_digest char(64) NOT NULL,
  out_trade_no_digest char(64) NOT NULL,
  refund_id_digest char(64) NOT NULL DEFAULT '',
  notification_route_digest char(64) NOT NULL,
  payment_config_id bigint NOT NULL,
  payment_config_fingerprint char(64) NOT NULL,
  final_status varchar(32) NOT NULL,
  final_callback_status varchar(32) NOT NULL,
  refund_amount_cent bigint NOT NULL,
  purged_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_purged_refund_no UNIQUE (out_refund_no_digest),
  CONSTRAINT uk_purged_refund_route UNIQUE (notification_route_digest),
  INDEX fk_purged_refund_archive (archive_manifest_id),
  INDEX idx_purged_refund_trade (out_trade_no_digest),
  INDEX idx_purged_refund_provider_id (refund_id_digest),
  INDEX idx_purged_refund_config (payment_config_id),
  INDEX idx_purged_refund_purged (purged_at,id),
  CONSTRAINT fk_purged_refund_archive FOREIGN KEY (archive_manifest_id) REFERENCES order_archive_manifest (id) ON DELETE RESTRICT,
  CONSTRAINT chk_purged_refund_amount CHECK ((refund_amount_cent > 0)),
  CONSTRAINT chk_purged_refund_config_fingerprint CHECK (char_length(payment_config_fingerprint) = 64),
  CONSTRAINT chk_purged_refund_notification_route CHECK (char_length(notification_route_digest) = 64)
);

CREATE TABLE finance_reconciliation_difference (
  id bigint NOT NULL AUTO_INCREMENT,
  batch_id bigint NOT NULL,
  diff_key char(64) NOT NULL,
  difference_type varchar(40) NOT NULL,
  severity varchar(16) NOT NULL,
  status varchar(24) NOT NULL DEFAULT 'OPEN',
  transaction_id varchar(64) NOT NULL DEFAULT '',
  out_trade_no varchar(64) NOT NULL DEFAULT '',
  refund_id varchar(64) NOT NULL DEFAULT '',
  out_refund_no varchar(64) NOT NULL DEFAULT '',
  order_id bigint DEFAULT NULL,
  payment_order_id bigint DEFAULT NULL,
  refund_order_id bigint DEFAULT NULL,
  provider_amount_cent bigint DEFAULT NULL,
  local_amount_cent bigint DEFAULT NULL,
  provider_status varchar(32) NOT NULL DEFAULT '',
  local_status varchar(32) NOT NULL DEFAULT '',
  provider_evidence text NOT NULL,
  local_evidence text NOT NULL,
  candidate_content_sha256 char(64) NOT NULL DEFAULT '',
  candidate_storage_provider varchar(32) NOT NULL DEFAULT '',
  candidate_storage_container varchar(128) NOT NULL DEFAULT '',
  candidate_storage_region varchar(64) NOT NULL DEFAULT '',
  candidate_object_key varchar(512) NOT NULL DEFAULT '',
  candidate_size_bytes bigint DEFAULT NULL,
  resolution_code varchar(64) NOT NULL DEFAULT '',
  resolution_reason varchar(500) NOT NULL DEFAULT '',
  resolved_by bigint DEFAULT NULL,
  resolved_at timestamp NULL DEFAULT NULL,
  version bigint NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  external_refund_applied BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id),
  CONSTRAINT uk_finance_reconciliation_difference UNIQUE (batch_id,diff_key),
  INDEX idx_finance_reconciliation_difference_batch_status (batch_id,status,difference_type,id),
  INDEX idx_finance_reconciliation_difference_payment_status (payment_order_id,status,id),
  INDEX idx_finance_reconciliation_difference_refund_status (refund_order_id,status,id),
  INDEX idx_finance_reconciliation_difference_order_status (order_id,status,id),
  INDEX idx_finance_reconciliation_external_refund (external_refund_applied,status,id),
  CONSTRAINT fk_finance_reconciliation_difference_batch FOREIGN KEY (batch_id) REFERENCES finance_reconciliation_batch (id) ON DELETE RESTRICT,
  CONSTRAINT fk_finance_reconciliation_difference_order FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_reconciliation_difference_payment FOREIGN KEY (payment_order_id) REFERENCES payment_order (id) ON DELETE SET NULL,
  CONSTRAINT fk_finance_reconciliation_difference_refund FOREIGN KEY (refund_order_id) REFERENCES refund_order (id) ON DELETE SET NULL,
  CONSTRAINT chk_finance_reconciliation_difference_candidate CHECK ((((candidate_content_sha256 = '') and (candidate_storage_provider = '') and (candidate_storage_container = '') and (candidate_storage_region = '') and (candidate_object_key = '') and (candidate_size_bytes is null)) or ((difference_type = 'SOURCE_CHANGED') and (char_length(candidate_content_sha256) = 64) and (candidate_storage_provider <> '') and (candidate_storage_container <> '') and (candidate_object_key <> '') and (candidate_size_bytes is not null) and (candidate_size_bytes >= 0)))),
  CONSTRAINT chk_finance_reconciliation_difference_severity CHECK ((severity in ('INFO','WARNING','CRITICAL'))),
  CONSTRAINT chk_finance_reconciliation_difference_status CHECK ((status in ('OPEN','INVESTIGATING','RESOLVED','AUTO_CLEARED'))),
  CONSTRAINT chk_finance_reconciliation_difference_type CHECK ((difference_type in ('CHANNEL_ONLY','LOCAL_ONLY','AMOUNT_MISMATCH','IDENTITY_MISMATCH','STATUS_MISMATCH','DUPLICATE_CHANNEL_ROW','SOURCE_CHANGED')))
);

CREATE TABLE order_cleanup_failure (
  source_order_id bigint NOT NULL,
  consecutive_failures int NOT NULL DEFAULT '1',
  next_retry_at timestamp NOT NULL,
  last_error varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (source_order_id),
  INDEX idx_order_cleanup_failure_retry (next_retry_at,source_order_id),
  CONSTRAINT fk_order_cleanup_failure_order FOREIGN KEY (source_order_id) REFERENCES shop_order (id) ON DELETE CASCADE,
  CONSTRAINT chk_order_cleanup_failure_count CHECK ((consecutive_failures > 0))
);

CREATE TABLE finance_external_refund (
  id bigint NOT NULL AUTO_INCREMENT,
  difference_id bigint NOT NULL,
  batch_id bigint NOT NULL,
  order_id bigint NOT NULL,
  payment_order_id bigint NOT NULL,
  provider_identity_key char(64) NOT NULL,
  mch_id varchar(64) NOT NULL,
  transaction_id varchar(64) NOT NULL DEFAULT '',
  out_trade_no varchar(64) NOT NULL DEFAULT '',
  refund_id varchar(64) NOT NULL DEFAULT '',
  out_refund_no varchar(64) NOT NULL DEFAULT '',
  amount_cent bigint NOT NULL,
  currency varchar(16) NOT NULL,
  provider_status varchar(32) NOT NULL,
  occurred_at timestamp NOT NULL,
  row_digest char(64) NOT NULL,
  reason varchar(500) NOT NULL,
  recorded_by bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_finance_external_refund_difference UNIQUE (difference_id),
  CONSTRAINT uk_finance_external_refund_identity UNIQUE (provider_identity_key),
  INDEX fk_finance_external_refund_batch (batch_id),
  INDEX idx_finance_external_refund_order (order_id,occurred_at,id),
  INDEX idx_finance_external_refund_payment (payment_order_id,occurred_at,id),
  CONSTRAINT fk_finance_external_refund_batch FOREIGN KEY (batch_id) REFERENCES finance_reconciliation_batch (id) ON DELETE RESTRICT,
  CONSTRAINT fk_finance_external_refund_difference FOREIGN KEY (difference_id) REFERENCES finance_reconciliation_difference (id) ON DELETE RESTRICT,
  CONSTRAINT fk_finance_external_refund_order FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE RESTRICT,
  CONSTRAINT fk_finance_external_refund_payment FOREIGN KEY (payment_order_id) REFERENCES payment_order (id) ON DELETE RESTRICT,
  CONSTRAINT chk_finance_external_refund_amount CHECK ((amount_cent > 0)),
  CONSTRAINT chk_finance_external_refund_currency CHECK ((currency = 'CNY')),
  CONSTRAINT chk_finance_external_refund_identity_present CHECK (((refund_id <> '') or (out_refund_no <> ''))),
  CONSTRAINT chk_finance_external_refund_status CHECK ((provider_status = 'SUCCESS'))
);

CREATE TABLE finance_reconciliation_resolution_audit (
  id bigint NOT NULL AUTO_INCREMENT,
  batch_id bigint DEFAULT NULL,
  difference_id bigint DEFAULT NULL,
  from_status varchar(24) NOT NULL,
  to_status varchar(24) NOT NULL,
  action varchar(32) NOT NULL,
  resolution_code varchar(64) NOT NULL DEFAULT '',
  reason varchar(500) NOT NULL,
  metadata varchar(1000) NOT NULL DEFAULT '',
  operator_id bigint DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_finance_reconciliation_resolution_time (difference_id,created_at,id),
  INDEX idx_finance_reconciliation_batch_audit_time (batch_id,created_at,id),
  CONSTRAINT fk_finance_reconciliation_resolution_batch FOREIGN KEY (batch_id) REFERENCES finance_reconciliation_batch (id) ON DELETE RESTRICT,
  CONSTRAINT fk_finance_reconciliation_resolution_difference FOREIGN KEY (difference_id) REFERENCES finance_reconciliation_difference (id) ON DELETE RESTRICT,
  CONSTRAINT chk_finance_reconciliation_resolution_action CHECK ((action in ('RUN','RETRY','SOURCE_DOWNLOAD','EXPORT','INVESTIGATE','RESOLVE','AUTO_CLEAR','REOPEN')))
);
