package org.muybaby.shopserver.common.error;

public enum ErrorCode {
    AUTHENTICATION_REQUIRED(100001, "Authentication required"),
    INVALID_CREDENTIALS(100002, "Invalid username or password"),
    PERMISSION_DENIED(100003, "Permission denied"),
    TOKEN_EXPIRED(100004, "Token expired"),
    ADMIN_LOGIN_RATE_LIMITED(100005, "Too many login attempts; try again later"),
    VALIDATION_FAILED(100400, "Validation failed"),
    RESOURCE_NOT_FOUND(100404, "Resource not found"),
    AUTHENTICATION_TEMPORARILY_UNAVAILABLE(100503, "Authentication temporarily unavailable"),
    INTERNAL_ERROR(100500, "Internal server error"),
    ANALYTICS_RATE_LIMITED(100429, "Too many analytics events"),
    ADMIN_USER_UNAVAILABLE(110001, "Admin user unavailable"),
    ADMIN_USERNAME_CONFLICT(110002, "Admin username already exists"),
    ADMIN_ROLE_UNAVAILABLE(110003, "Admin role unavailable"),
    ADMIN_ROLE_CODE_CONFLICT(110004, "Admin role code already exists"),
    ADMIN_ROLE_IN_USE(110005, "Admin role is assigned to users"),
    CURRENT_ADMIN_DISABLE_FORBIDDEN(110006, "Current admin user cannot be disabled"),
    ADMIN_ROLE_GRANT_INVALID(110007, "Role grant must include parent and owning menus"),
    DATA_CLEANUP_CONFIG_CONFLICT(110008, "数据清理配置已被其他管理员修改，请刷新后重试"),
    ADMIN_REGISTRATION_DISABLED(110009, "管理后台注册当前未开放"),
    ADMIN_REGISTRATION_SETTING_UNAVAILABLE(110010, "管理后台注册配置不可用"),
    ADMIN_CURRENT_PASSWORD_INVALID(110011, "当前密码不正确"),
    WECHAT_LOGIN_FAILED(100101, "WeChat login failed"),
    WECHAT_PHONE_FAILED(100102, "WeChat phone authorization failed"),
    APP_USER_UNAVAILABLE(100103, "App user unavailable"),
    APP_USER_AVATAR_RATE_LIMITED(100104, "每天最多修改 3 次头像，请明天再试"),
    ACCOUNT_RIGHTS_REQUEST_UNAVAILABLE(120001, "账户权利申请不存在或不可用"),
    ACCOUNT_RIGHTS_REQUEST_CONFLICT(120002, "已有进行中的账户权利申请"),
    ACCOUNT_RIGHTS_STATE_CONFLICT(120003, "账户权利申请状态已变化，请刷新后重试"),
    ACCOUNT_CANCELLATION_IDENTITY_MISMATCH(120004, "微信身份校验失败，请重新获取登录凭证"),
    ACCOUNT_CANCELLATION_ACTIVE_OBLIGATIONS(120005, "仍有进行中的交易、支付、退款或售后事项"),
    FINANCE_RECONCILIATION_DISABLED(130001, "微信交易账单对账当前未启用"),
    FINANCE_RECONCILIATION_UNAVAILABLE(130002, "财务对账批次不存在或当前不可用"),
    FINANCE_RECONCILIATION_CONFLICT(130003, "财务对账状态已变化，请刷新后重试"),
    FINANCE_RECONCILIATION_SOURCE_UNAVAILABLE(130004, "原始交易账单暂不可用"),
    FINANCE_EXPORT_LIMIT_EXCEEDED(130005, "财务导出范围或行数超过限制"),
    FINANCE_RECONCILIATION_RUNTIME_CONFLICT(130006, "财务对账运行配置已被其他管理员修改，请刷新后重试"),
    PRODUCT_CATEGORY_UNAVAILABLE(200000, "商品分类不存在或当前不可用"),
    PRODUCT_UNAVAILABLE(200001, "Product unavailable"),
    SKU_UNAVAILABLE(200002, "SKU unavailable"),
    PRODUCT_NOT_IN_RECYCLE_BIN(200003, "Product is not in recycle bin"),
    PRODUCT_PURGE_CONFIRMATION_MISMATCH(200004, "Product title confirmation does not match"),
    PRODUCT_PURGE_HAS_LOCKED_STOCK(200005, "Product has locked stock and cannot be permanently deleted"),
    PRODUCT_PURGE_HAS_ACTIVE_BANNER(200006, "Product is referenced by an enabled banner and cannot be permanently deleted"),
    PRODUCT_PURGE_HAS_ACTIVE_HOME_ITEM(200007, "Product is referenced by an enabled home placement and cannot be permanently deleted"),
    PRODUCT_CATEGORY_CYCLE(200008, "Product category cycle is not allowed"),
    PRODUCT_REVIEW_NOT_FOUND(200200, "Product review not found"),
    PRODUCT_REVIEW_NOT_ELIGIBLE(200201, "Only completed purchases can be reviewed"),
    PRODUCT_REVIEW_ALREADY_EXISTS(200202, "This order item has already been reviewed"),
    STOCK_SHORTAGE(200100, "Stock shortage"),
    CART_ITEM_NOT_FOUND(250001, "Cart item not found"),
    COUPON_UNAVAILABLE(300001, "Coupon unavailable"),
    COUPON_CLAIM_LIMIT_REACHED(300002, "Coupon claim limit reached"),
    COUPON_ALREADY_USED(300003, "Coupon already used"),
    ORDER_STATE_CONFLICT(400001, "Order state conflict"),
    PAYMENT_PENDING(500001, "Payment pending"),
    PAYMENT_CONFIGURATION_CHANGED(500002, "Payment configuration changed; manual reconciliation required"),
    WECHAT_SHIPPING_UPLOAD_FAILED(600001, "WeChat shipping upload failed"),
    WECHAT_RECEIPT_NOT_CONFIRMED(600002, "微信尚未确认收货，请完成确认后重试"),
    WECHAT_RECEIPT_STATUS_UNAVAILABLE(600003, "微信收货状态暂时无法确认，请稍后重试"),
    WECHAT_EXPRESS_CONFIG_CONFLICT(600004, "电子面单配置已被其他管理员修改，请刷新后重试"),
    WECHAT_WAYBILL_REGISTRATION_UNAVAILABLE(600005, "物流查询暂不可用，请稍后重试"),
    WECHAT_WAYBILL_CONFLICT(600006, "电子面单状态已变化，请刷新后重试"),
    WECHAT_WAYBILL_UNAVAILABLE(600007, "微信电子面单服务暂不可用，请稍后重试"),
    WECHAT_SERVICE_CARD_RUNTIME_CONFLICT(600008, "微信服务动态运行配置已被其他管理员修改，请刷新后重试"),
    WECHAT_SHIPPING_RUNTIME_CONFLICT(600009, "微信发货运行配置已被其他管理员修改，请刷新后重试"),
    WECHAT_PLATFORM_CONFIG_UNAVAILABLE(600010, "微信平台配置不可用"),
    WECHAT_PLATFORM_CONFIG_CONFLICT(600011, "微信平台配置已被其他管理员修改，请刷新后重试"),
    WECHAT_SERVICE_CARD_CONFIG_UNAVAILABLE(600012, "微信服务动态接入配置不可用"),
    WECHAT_SERVICE_CARD_CONFIG_CONFLICT(600013, "微信服务动态接入配置已被其他管理员修改，请刷新后重试"),
    WECHAT_REFUND_FAILED(700001, "WeChat refund failed"),
    STORAGE_FILE_UNAVAILABLE(800001, "Storage file unavailable"),
    STORAGE_UPLOAD_POLICY_REJECTED(800002, "Storage upload policy rejected"),
    STORAGE_FILE_IN_USE(800003, "Storage file in use"),
    STORAGE_ASSET_FOLDER_UNAVAILABLE(800004, "Storage asset folder unavailable"),
    STORAGE_ASSET_FOLDER_IN_USE(800005, "Storage asset folder is not empty"),
    STORAGE_ASSET_FOLDER_CYCLE(800006, "Storage asset folder cycle is not allowed"),
    STORAGE_IMAGE_PROCESSING_FAILED(800007, "COS 图片处理暂时失败，请稍后重试"),
    STORAGE_NOT_CONFIGURED(800008, "腾讯云 COS 尚未配置，请先在管理后台完成对象存储配置"),
    STORAGE_DIRECT_UPLOAD_UNAVAILABLE(800009, "该文件暂不支持 COS 直传，请使用兼容上传方式"),
    STORAGE_DIRECT_UPLOAD_RATE_LIMITED(800010, "图片上传过于频繁，请稍后重试"),
    STORAGE_CUSTOM_DOMAIN_NOT_BOUND(800011, "COS 自定义域名未在当前存储桶中启用为默认源站"),
    STORAGE_CUSTOM_DOMAIN_VERIFICATION_FAILED(800012, "COS 自定义域名验证失败，请检查存储桶、地域、密钥及 GetBucketDomain 权限"),
    STORAGE_CUSTOM_DOMAIN_VERIFICATION_UNAVAILABLE(800013, "COS 自定义域名验证服务暂时不可用，请稍后重试"),
    CUSTOMER_SERVICE_CONVERSATION_UNAVAILABLE(900001, "Customer service conversation unavailable"),
    CUSTOMER_SERVICE_STATE_CONFLICT(900002, "Customer service conversation state conflict"),
    CUSTOMER_SERVICE_ASSIGNMENT_REQUIRED(900003, "Customer service assignment required"),
    CUSTOMER_SERVICE_ORDER_UNAVAILABLE(900004, "Customer service order unavailable"),
    CUSTOMER_SERVICE_AGENT_NOT_AVAILABLE(900005, "Customer service agent is not available"),
    CUSTOMER_SERVICE_AGENT_CAPACITY_REACHED(900006, "Customer service agent capacity reached"),
    CUSTOMER_SERVICE_TRANSFER_UNAVAILABLE(900007, "Customer service transfer request unavailable"),
    CUSTOMER_SERVICE_TRANSFER_PENDING(900008, "Customer service transfer request already pending"),
    CUSTOMER_SERVICE_AGENT_HAS_ACTIVE_CONVERSATIONS(900009, "客服仍有进行中的会话，暂时不能移除"),
    CUSTOMER_SERVICE_CONFIG_INVALID(900010, "客服配置无效");

    private final int code;
    private final String message;

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int code() {
        return code;
    }

    public String message() {
        return message;
    }
}
